class CreateTableHelpdeskSchemaLessTickets < ActiveRecord::Migration
  def self.up
  	execute("create table helpdesk_schema_less_tickets (
			id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
			account_id bigint(20) unsigned DEFAULT NULL,
			ticket_id bigint(20) unsigned DEFAULT NULL,
			product_id bigint(20) unsigned DEFAULT NULL,
			to_emails text COLLATE utf8_unicode_ci,
			long_tc01 bigint(20) unsigned DEFAULT NULL,
			long_tc02 bigint(20) unsigned DEFAULT NULL,
			long_tc03 bigint(20) unsigned DEFAULT NULL,
			long_tc04 bigint(20) unsigned DEFAULT NULL,
			long_tc05 bigint(20) unsigned DEFAULT NULL,
			long_tc06 bigint(20) unsigned DEFAULT NULL,
			long_tc07 bigint(20) unsigned DEFAULT NULL,
			long_tc08 bigint(20) unsigned DEFAULT NULL,
			long_tc09 bigint(20) unsigned DEFAULT NULL,
			long_tc10 bigint(20) unsigned DEFAULT NULL,
			int_tc01 int(11) DEFAULT NULL,
			int_tc02 int(11) DEFAULT NULL,
			int_tc03 int(11) DEFAULT NULL,
			int_tc04 int(11) DEFAULT NULL,
			int_tc05 int(11) DEFAULT NULL,
			string_tc01 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc02 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc03 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc04 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc05 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc06 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc07 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc08 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc09 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc10 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc11 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc12 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc13 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc14 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			string_tc15 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
			datetime_tc01 datetime DEFAULT NULL,
			datetime_tc02 datetime DEFAULT NULL,
			datetime_tc03 datetime DEFAULT NULL,
			datetime_tc04 datetime DEFAULT NULL,
			datetime_tc05 datetime DEFAULT NULL,
			boolean_tc01 tinyint(1) DEFAULT false,
			boolean_tc02 tinyint(1) DEFAULT false,
			boolean_tc03 tinyint(1) DEFAULT false,
			boolean_tc04 tinyint(1) DEFAULT false,
			boolean_tc05 tinyint(1) DEFAULT false,
			text_tc01 text COLLATE utf8_unicode_ci,
			text_tc02 text COLLATE utf8_unicode_ci,
			text_tc03 text COLLATE utf8_unicode_ci,
			text_tc04 text COLLATE utf8_unicode_ci,
			text_tc05 text COLLATE utf8_unicode_ci,
			created_at datetime DEFAULT NULL,
			updated_at datetime DEFAULT NULL,
			KEY helpdesk_schema_less_tickets_id (id),
			UNIQUE  KEY index_helpdesk_schema_less_tickets_on_account_id_ticket_id (ticket_id , account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_product_id(account_id, product_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_long_01(long_tc01, account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_long_02(long_tc02, account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_int_01(int_tc01, account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_int_02(int_tc02, account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_string_01(string_tc01(10), account_id),
			KEY index_helpdesk_schema_less_tickets_on_ticket_id_and_string_02(string_tc02(10), account_id)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PARTITION BY  HASH(account_id) PARTITIONS 128"
		)
  end

  def self.down
  	drop_table :helpdesk_schema_less_tickets
  end
end
