settings:
  :helpdesk_tickets_by_product:
    default: false
    internal: false
    feature_dependency: :multi_product # Caution! Temporary! Dependency yet to be provided by the product
  :solutions_agent_metrics:
    default: false
    internal: false
    feature_dependency: :solutions_agent_metrics_feature
  :untitled_setting_3:
    default: true
    internal: false
    feature_dependency: :untitled_feature_2_dependency_toggle # from estate plan.Rename to actual feature
  :untitled_setting_4:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
