settings:
  :es_v2_splqueries:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :force_index_tickets:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :skip_portal_cname_chk:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :branding:
    default: true
    internal: false
    feature_dependency: :branding_feature
  :solutions_agent_metrics:
    default: false
    internal: false
    feature_dependency: :solutions_agent_metrics_feature
  :stop_contacts_count_query:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :spam_blacklist_feature:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :skip_invoice_due_warning:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :fb_msg_realtime:
    default: false
    interal: true
    feature_dependency: :basic_settings_feature
  :sidekiq_logs_to_central:
    default: false
    interal: true
    feature_dependency: :basic_settings_feature
  :personalized_email_replies:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :allow_huge_ccs:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :compose_email:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :reply_to_based_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :disable_agent_forward:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :disable_supress_logs:
    default: false
    interal: true
    feature_dependency: :basic_settings_feature
  :fetch_ticket_from_ref_first:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :skip_ticket_threading:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :allow_wildcard_ticket_create:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :signup_link:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :anonymous_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :captcha:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :auto_suggest_solutions:
    default: true
    internal: false
    feature_dependency: :allow_auto_suggest_solutions
  :public_ticket_url:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :open_solutions:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :sort_by_customer_response:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :open_forums:
    default: false
    internal: false
    feature_dependency: :forums
  :hide_portal_forums:
    default: false
    internal: false
    feature_dependency: :forums
  :filter_factory:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :new_es_api:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :forum_captcha_disable:
    default: false
    internal: false
    feature_dependency: :forums
  :kb_allow_base64_images:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :moderate_posts_with_links:
    default: true
    internal: false
    feature_dependency: :forums
  :moderate_all_posts:
    default: false
    internal: false
    feature_dependency: :forums
  :es_multilang_solutions:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :helpdesk_tickets_by_product:
    default: false
    internal: false
    feature_dependency: :multi_product
  :ticket_summary:
    default: false
    internal: false
    feature_dependency: :ticket_summary_feature
  :disable_freshchat:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :cascade_dispatcher:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :euc_hide_agent_metrics:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :secure_attachments:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :feedback_widget_captcha:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :gamification_perf:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :location_tagging:
    default: false
    internal: false
    feature_dependency: :field_service_management_toggle
    settings_dependency: :field_service_management
  :field_service_geolocation:
    default: false
    internal: false
    feature_dependency: :field_service_management_toggle
    settings_dependency: :field_service_management
  :bypass_signup_captcha:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :parent_child_infra:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature # temporary implementation. Will be changed when multiple dependency features are supported.
  :custom_product_notification:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :disable_emails:
    default: false
    interal: true
    feature_dependency: :basic_settings_feature
  :disable_archive:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :caching:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :secure_fields:
    default: false
    internal: false
    feature_dependency: :secure_fields_toggle
