settings:
  :untitled_setting_1:
    default: false
    internal: false
    feature_dependency: :untitled_feature_1_dependency_toggle # from blossom plan.Rename to actual feature
  :untitled_setting_2:
    default: true
    internal: true
    feature_dependency: :untitled_feature_1_dependency_toggle
  :untitled_setting_3:
    default: true
    internal: false
    feature_dependency: :untitled_feature_2_dependency_toggle # from estate plan.Rename to actual feature
  :untitled_setting_4:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :personalized_email_replies:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
    :compose_email:
      default: false
      internal: false
      feature_dependency: :basic_settings_feature
    :reply_to_based_tickets:
      default: true
      internal: false
      feature_dependency: :basic_settings_feature
    :disable_agent_forward:
      default: false
      internal: false
      feature_dependency: :basic_settings_feature