settings:
  :untitled_setting_1:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :branding:
    default: true
    internal: false
    feature_dependency: :branding_feature
  :solutions_agent_metrics:
    default: false
    internal: false
    feature_dependency: :solutions_agent_metrics_feature
  :untitled_setting_4:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :skip_invoice_due_warning:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :personalized_email_replies:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :compose_email:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :reply_to_based_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :disable_agent_forward:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :fetch_ticket_from_ref_first:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :skip_ticket_threading:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :allow_wildcard_ticket_create:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :signup_link:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :anonymous_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :auto_suggest_solutions:
    default: true
    internal: false
    feature_dependency: :allow_auto_suggest_solutions
  :public_ticket_url:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :open_solutions:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :sort_by_customer_response:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :open_forums:
    default: false
    internal: false
    feature_dependency: :forums
  :filter_factory:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :new_es_api:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :forum_captcha_disable:
    default: false
    internal: false
    feature_dependency: :forums
  :kb_allow_base64_images:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :moderate_posts_with_links:
    default: true
    internal: false
    feature_dependency: :forums
  :moderate_all_posts:
    default: false
    internal: false
    feature_dependency: :forums
  :es_multilang_solutions:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :helpdesk_tickets_by_product:
    default: false
    internal: false
    feature_dependency: :multi_product
  :ticket_summary:
    default: false
    internal: false
    feature_dependency: :ticket_summary_feature
  :disable_freshchat:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :cascade_dispatcher:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :feedback_widget_captcha:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
  :gamification_perf:
    default: false
    internal: true
    feature_dependency: :basic_settings_feature
