settings:
  :untitled_setting_1:
    default: false
    internal: false
    feature_dependency: :untitled_feature_1_dependency_toggle # from blossom plan.Rename to actual feature
  :untitled_setting_2:
    default: true
    internal: true
    feature_dependency: :untitled_feature_1_dependency_toggle
  :solutions_agent_metrics:
    default: true
    internal: false
    feature_dependency: :solutions_agent_metrics_feature
  :untitled_setting_4:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :signup_link:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :anonymous_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :auto_suggest_solutions:
    default: true
    internal: false
    feature_dependency: :allow_auto_suggest_solutions
  :public_ticket_url:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :open_solutions:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :open_forums:
    default: false
    internal: false
    feature_dependency: :forums
  :forum_captcha_disable:
    default: false
    internal: false
    feature_dependency: :forums
  :moderate_posts_with_links:
    default: true
    internal: false
    feature_dependency: :forums
  :moderate_all_posts:
    default: false
    internal: false
    feature_dependency: :forums
  :helpdesk_tickets_by_product:
    default: false
    internal: false
    feature_dependency: :multi_product
  :solutions_agent_metrics:
    default: false
    internal: false
    feature_dependency: :solutions_agent_metrics_feature
