settings:
  :signup_link:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :anonymous_tickets:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :auto_suggest_solutions:
    default: true
    internal: false
    feature_dependency: :allow_auto_suggest_solutions
  :public_ticket_url:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :open_solutions:
    default: true
    internal: false
    feature_dependency: :basic_settings_feature
  :cascade_dispatcher:
    default: false
    internal: false
    feature_dependency: :basic_settings_feature
  :open_forums:
    default: false
    internal: false
    feature_dependency: :forums
  :forum_captcha_disable:
    default: false
    internal: false
    feature_dependency: :forums
  :moderate_posts_with_links:
    default: true
    internal: false
    feature_dependency: :forums
  :moderate_all_posts:
    default: false
    internal: false
    feature_dependency: :forums
