module FeatureConstants
  DISCUSSION = :forums
  TIME_ENTRIES = :timesheets
  WATCHERS = :add_watcher
  PRODUCTS = :multi_product
  TICKETS = :compose_email
  REQUESTER_WIDGET = :requester_widget
  SURVEYS = [:surveys].freeze
  SATISFACTION_RATINGS = [:surveys].freeze
  SATISFACTION_RATINGS_WITH_LINK = SATISFACTION_RATINGS | [:survey_links]
  BOT = :support_bot
  TICKET_TEMPLATES = [:ticket_templates]
  TICKET_FIELDS = [:custom_ticket_fields].freeze
  ENCRYPTED_FIELDS = [:denormalized_flexifields, :hipaa, :custom_encrypted_fields].freeze
  CONTACT_COMPANY_NOTES = :contact_company_notes
  CANNED_FORMS = :canned_forms
  SANDBOX = :sandbox
  BOT_EMAIL_CHANNEL = :bot_email_channel.freeze
  BOT_CHAT_HISTORY = :bot_chat_history.freeze
  AUTOMATION_REVAMP = :automation_revamp.freeze
  ARCHIVE_API = :archive_tickets_api
  AUTOFAQ = :autofaq
  BOTFLOW = :botflow
  HELP_WIDGET = :help_widget
  AGENT_ARTICLES_SUGGEST = :agent_articles_suggest
  TICKET_FIELD_REVAMP = :ticket_field_revamp
  AGENT_SHIFTS = :agent_shifts.freeze
  OUT_OF_OFFICE = :out_of_office
  AGENT_STATUSES = :agent_statuses
  SOLUTIONS_TEMPLATES = :solutions_templates
  OMNI_AGENT_AVAILABILITY_DASHBOARD = :omni_agent_availability_dashboard
end
