type: object
description: Available only if the property has to be updated
properties:
  field_agents_can_manage_appointments:
    type: boolean
  location_tagging_enabled:
    type: boolean
  geo_location_enabled:
    type: boolean