all:
  exclude:
    - 'spec/**/*'
eslint:
  exclude:
    - 'app/assets/**/*'
github:
  slug: freshdesk/helpkit
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
<<<<<<< HEAD
=======
github_pr:
  format: "%{runner}:%{level}: %{msg}"
>>>>>>> origin/staging
max_warnings: 150
verbose: false
