all:
  exclude:
    - 'spec/**/*'
    - 'Gemfile.lock'
    - 'Gemfile'
eslint:
  exclude:
    - 'app/assets/**/*'
github:
  slug: freshdesk/helpkit
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
github_pr:
  format: "%{runner}:%{level}: %{msg}"
max_warnings: 150
verbose: false
