all:
  exclude:
    - 'spec/**/*'
eslint:
  exclude:
    - 'app/assets/**/*'
github:
  slug: freshdesk/helpkit
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 150
verbose: false
