inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true
AllCops:
  Include:
    - '**/*.api'
  Exclude:
    - 'test/api/query_reports/*'

Metrics/LineLength:
  Enabled: false
  
Rails/DynamicFindBy:
  Enabled: false

Rails/ActionFilter:
  Enabled: false