--- 
development: 
  :tenant: tenant_info_dev
  :cluster: cluster_info_dev
test: 
  :tenant: tenant_info_test
  :cluster: cluster_info_test
staging: 
  :tenant: tenant_info_staging
  :cluster: cluster_info_staging
