get:
  tags: [Configs]
  summary: Configs Show
  parameters:
    - name: id
      in: path
      type: string
      description: Config Information
      required: true
  responses:
    200:
      description: Success
      schema:
        $ref: '#/definitions/configs_show'
    400:
      description: Bad request error
      schema:
        $ref: '#/definitions/bad_request_error'
    403:
      description: Access denied
