module Redis::Keys::AutomationRules
  AUTOMATION_RULES_BY_DATE = 'AUTOMATION_RULE:%{account_id}:%{mm}:%{dd}'
  AUTOMATION_RULE_ID = 'AUTOMATION_RULE_ID:%{rule_id}'
  THANK_YOU_NOTE_CONFIDENCE = 'THANK_YOU_NOTE_CONFIDENCE'.freeze
  AUTOMATION_RULES_WITH_THANK_YOU_CONFIGURED = 'AUTOMATION_RULES_WITH_THANK_YOU_CONFIGURED:%{account_id}'.freeze
end
