module Redis::Keys::RateLimit
  
  API_THROTTLER                 = "API_THROTTLER:%{host}".freeze
  API_THROTTLER_V2              = "API_THROTTLER_V2:%{account_id}".freeze
  ACCOUNT_API_LIMIT             = "ACCOUNT_API_LIMIT:%{account_id}".freeze
  DEFAULT_API_LIMIT             = "DEFAULT_API_LIMIT".freeze
  PLAN_API_LIMIT                = "PLAN_API_LIMIT:%{plan_id}".freeze
  PLAN_API_MIN_LIMIT            = "PLAN_API_MIN_LIMIT:%{plan_id}".freeze
  PLAN_API_MIN_PATHS_LIMIT      = "PLAN_API_MIN_PATHS_LIMIT:%{plan_id}".freeze
  DEFAULT_API_MIN_LIMIT         = 'DEFAULT_API_MIN_LIMIT'.freeze
  PRIVATE_API_THROTTLER         = "PRIVATE_API_THROTTLER:%{account_id}".freeze
  ACCOUNT_PRIVATE_API_LIMIT     = "ACCOUNT_PRIVATE_API_LIMIT:%{account_id}".freeze
  DEFAULT_PRIVATE_API_LIMIT     = "DEFAULT_PRIVATE_API_LIMIT".freeze
  HAPROXY_IP_BLACKLIST_KEY      = "HAPROXY_IP_BLACKLIST_KEY".freeze
  HAPROXY_DOMAIN_BLACKLIST_KEY  = "HAPROXY_DOMAIN_BLACKLIST_KEY".freeze
  HAPROXY_IP_BLACKLIST_CHANNEL  = "HAPROXY_IP_BLACKLIST_CHANNEL".freeze
  CHANNEL_API_THROTTLER         = "CHANNEL_API_THROTTLER:%{account_id}".freeze
  ACCOUNT_CHANNEL_API_LIMIT     = "ACCOUNT_CHANNEL_API_LIMIT".freeze
  DEFAULT_CHANNEL_API_LIMIT     = "DEFAULT_CHANNEL_API_LIMIT".freeze
  WIDGET_API_THROTTLER          = "WIDGET_API_THROTTLER:%{account_id}".freeze
  ACCOUNT_WIDGET_API_LIMIT      = "ACCOUNT_WIDGET_API_LIMIT:%{account_id}".freeze
  DEFAULT_WIDGET_API_LIMIT      = "DEFAULT_WIDGET_API_LIMIT".freeze
  PLAN_EMAIL_LIMIT              = 'PLAN_EMAIL_LIMIT:%{plan_id}'.freeze
  PLAN_EMAIL_PATHS_LIMIT        = 'PLAN_EMAIL_MIN_PATHS_LIMIT:%{plan_id}'.freeze
end