#!/bin/sh

# This commit hook validates the commit message for the following
#   - It should contains a JIRA id 

printMsg(){
  echo "$*"
  echo "----------------------------"
}

jiraIssuePattern="(FDCORE|FRESHPIPE|FRESHCALL|TH|FD)-(\\d+)"
commitMsgFile=$1

if [ -f ~/.jira_auth ]; then
  chmod +x ~/.jira_auth
  . ~/.jira_auth
else 
  echo "Missing JIRA auth file.Run the following command to setup.

bash script/githooks/setupGit
"
  exit 1;
fi


jiraId=`cat $1 | head -n 1 | egrep -o -m 1 "${jiraIssuePattern}"`
msgWordCount=`cat $1 | head -n 1 | tr -s ' ' '\n' | egrep -v "${jiraIssuePattern}" | wc -l`

#merge commit
if [ `git rev-parse -q --verify MERGE_HEAD | wc -c` -gt 1 ]
then 
  exit 0;
fi

#Sos for override
if [ `cat $1 | head -n 1 | grep SoS | wc -l` -gt 0 ] 
then 
  exit 0;
fi

if [ $msgWordCount -lt 3 ] 
then 
  printMsg "Please enter a decriptive commit msg title" 
  exit 1;
fi

if [ "$jiraId" == "" ] 
then 
  numIssueIdsInDesc=`cat $1 | egrep -o  "${jiraIssuePattern}" | wc -l | awk '{print $1}'`
  if [ $numIssueIdsInDesc -gt 0 ] 
    then
      printMsg "$numIssueIdsInDesc Jira Issue Id was found as part of the commit description. 
Please enter a valid Jira Id in the commit message instead."
    else
      read -r -d '' MSG << EndOfMessage 
Missing JIRA Issue id. The commit message needs to contain a valid JIRA Issue id.
Example : 

FDCORE-3352 : This is a sample commit message
EndOfMessage
      printMsg "$MSG"
  fi
  exit 1;
fi

command -v osascript &> /dev/null  && osascript -e 'display notification "Validating JIRA ID for commit" with title "Hang in there"'

curl -u "${JIRA_AUTH}" "Content-Type: application/json" -s "https://freshwave.atlassian.net/rest/api/2/issue/${jiraId}" > /tmp/jiraIssueResult.txt

if [ $? -ne 0  -o `cat /tmp/jiraIssueResult.txt | grep errorMessages | wc -l` -gt 0 ]
then
  echo "Error accessing Jira issues status. Could not complete commit."
  cat /tmp/jiraIssueResult.txt
  exit 1;
fi;

exit 0;
