#!/bin/sh

# This generates a default commit message

commitMsgFile=$1
type=$2 

#Don't apply FDCORE- commit message for merge commits
#And for non terminal git clients
if [ "$type" != "merge" -a -t 1 ] 
then 
  sed -i ' ' -e '1s/^/FDCORE\-\: /' $commitMsgFile
fi;
