#!/bin/bash

echo "Get your Freshrelease token from https://freshworks.freshrelease.com/api_token.json"
echo "Please enter your Freshrelease token "
read token

echo "FR_TOKEN='${token}'" > ~/.fr_auth
chmod +x ~/.fr_auth
echo "You are all set to commit"