version: '3.0'

services:
  redis32:
    image: redis:3.2-alpine #https://hub.docker.com/r/library/redis/tags/
    network_mode: "bridge"
    ports:
      - '6379:6379'
    container_name: redis32    

  mysql57:
    image: mysql:5.7 #https://hub.docker.com/r/library/mysql/tags/
    network_mode: "bridge"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    container_name: mysql57    

  memcached14:
    image: bitnami/memcached:latest #https://hub.docker.com/r/bitnami/memcached/ - this image has better logging support
    network_mode: "bridge"
    ports:
      - "11211:11211"
    container_name: memcached14

  localaws084:
    image: localstack/localstack:0.8.4
    network_mode: "bridge"
    ports:
      - "4569:4569" #dynamoDB
      - "4572:4572" #S3
      - "4576:4576" #SQS
      - "8080:8080" #localstack web
    container_name: localaws084
    environment:
        - USE_SSL=true
        - SERVICES=dynamodb,s3,sqs

      # - "4567-4578:4567-4578"
      # - "4574:4574" #lambda
      # - "4575:4575" #SNS      
      # - "4571:4571" #Elasticsearch
      # - "4578:4578" #ES service  