#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

module HelpdeskActivities
  module TicketActivitiesExport
    require 'thrift'
    require 'helpdesk_activities/activity_types'
    class Client
      include ::Thrift::Client

      def get_activities_export_file(act_export)
        send_get_activities_export_file(act_export)
        return recv_get_activities_export_file()
      end

      def send_get_activities_export_file(act_export)
        send_message('get_activities_export_file', Get_activities_export_file_args, :act_export => act_export)
      end

      def recv_get_activities_export_file()
        result = receive_message(Get_activities_export_file_result)
        return result.success unless result.success.nil?
        raise result.error unless result.error.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_activities_export_file failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_get_activities_export_file(seqid, iprot, oprot)
        args = read_args(iprot, Get_activities_export_file_args)
        result = Get_activities_export_file_result.new()
        begin
          result.success = @handler.get_activities_export_file(args.act_export)
        rescue ::HelpdeskActivities::TicketActivityExportException => error
          result.error = error
        end
        write_result(result, oprot, 'get_activities_export_file', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class Get_activities_export_file_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ACT_EXPORT = 1

      FIELDS = {
        ACT_EXPORT => {:type => ::Thrift::Types::STRUCT, :name => 'act_export', :class => ::HelpdeskActivities::ActivityExportRequest}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Get_activities_export_file_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0
      ERROR = 1

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::HelpdeskActivities::ActivityExportResponse}},
        ERROR => {:type => ::Thrift::Types::STRUCT, :name => 'error', :class => ::HelpdeskActivities::TicketActivityExportException}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
