type: object
properties:
  assignment_settings:
    description: sets a standard threshold value for all agents in ticket, chat and caller
    type: object
    properties:
      ticket:
        type: object
        properties:
          limit:
            type: integer
            minimum: 0
          assignment_preference:
            type: string
            description: calculates priority during ticket assignment based on one of the given properties
            enum: ['created_at', 'response_due', 'resolution_due']
      chat:
        type: object
        properties:
          limit:
            type: integer
            minimum: 0
      phone:
        type: object
        properties:
          limit:
            type: integer
            minimum: 0
            maximum: 1
          pause_assignment_on_call:
            type: boolean
            description: true indicates during call assignments will be paused
  agent_individual_limits_enabled:
    type: boolean
    description: true indicates individual capping limits for each agent is enabled

example:
  {
    assignment_settings: 
    {
      ticket:
      {
        limit: 10,
        preference: 'created_at'
      },
      chat:
      {
        limit: 10,
      },
      phone:
      {
        limit: 1,
        pause_assignment_on_call: true
      }
    },
    agent_individual_limits_enabled: true
  }
