
type: object
properties:
  product_feedback:
    type: object
    properties:
      description:
        type: string
      attachment_ids:
        type: array
        description: array of attachment IDs
        items:
          type: integer
