type: object
properties:
  id:
    type: number
  name:
    type: string
  description:
    type: string
  private:
    type: boolean
  actions:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
