type: object
properties:
  whitelisted_ips:
    type: object
    description: The app can be accessed only on the IPs listed here.
    properties:
      enabled:
        type: boolean
      applies_only_to_agents:
        type: boolean
        description: This IP range checks are applicable only to agents if this is true. And applicable to everyone if this is false.
      ip_ranges:
        type: array
        minItems: 1
        maxItems: 500
        items:
          type: object
          properties:
            start_ip:
              type: string
              format: ipaddress
              description: Denotes the starting IP
              example: '111.00.11.00'
            end_ip:
              type: string
              format: ipadress
              description: Denotes the ending IP
              example: '111.00.11.10'
  help_widget:
    type: object
    readOnly: true
    properties:
      key:
        type: string
  notification_emails:
    type: array
    description: List of emails for sending notifications
    uniqueItems: true
    items:
      type: string
      format: email
      example: ['ram@gmail.com']
  contact_password_policy:
    type: object
    properties:
      minimum_characters:
        type: integer
        description: Default password_policy. Cannot be set to null
        minimum: 8
        maximum: 99
      have_special_character:
        type: boolean
        description: Value should be set as nil for removing this policy
      atleast_an_alphabet_and_number:
        type: boolean
        description: Value should be set as nil for removing this policy
      password_expiry_in_days:
        type: integer
        enum: [30, 60, 90, 120, 150, 180]
        description: Default password_policy. Cannot be set to null
      have_mixed_case:
        type: boolean
        description: Value should be set as nil for removing this policy
      cannot_contain_user_name:
        type: boolean
        description: Default password_policy. Cannot be set to null
      cannot_be_same_as_past_passwords:
        type: integer
        minimum: 1
        maximum: 5
        description: Value should be set as nil for removing this policy
  agent_password_policy:
    type: object
    properties:
      minimum_characters:
        type: integer
        minimum: 8
        maximum: 99
        description: Default password_policy. Cannot be set to null
      have_special_character:
        type: boolean
        description: Value should be set as nil for removing this policy
      atleast_an_alphabet_and_number:
        type: boolean
        description: Value should be set as nil for removing this policy
      password_expiry_in_days:
        type: integer
        enum: [30, 60, 90, 120, 150, 180]
        description: Default password_policy. Cannot be set to null
      have_mixed_case:
        type: boolean
        description: Value should be set as nil for removing this policy
      cannot_contain_user_name:
        type: boolean
        description: Default password_policy. Cannot be set to null
      cannot_be_same_as_past_passwords:
        type: integer
        minimum: 1
        maximum: 5
        description: Value should be set as nil for removing this policy
