module Mobile::Constants
	MOBILE_NOTIFICATION_CHANNEL_COUNT = 5

	NOTIFCATION_TYPES = {
			:NEW_TICKET => :NEW_TICKET_NOTIFICATION,
			:TICKET_ASSIGNED => :TICKET_ASSIGNED_NOTIFICATION,
			:GROUP_ASSIGNED => :GROUP_ASSIGNED_NOTIFICATION,
			:NEW_RESPONSE => :NEW_RESPONSE_NOTIFICATION,
			:STATUS_UPDATE => :STATUS_UPDATE_NOTIFICATION
	}
end
