module CentralConstants
  # Note: Please follow this convention.
  # In case of addition(non-breaking changes on consumer) Bump the minor version. update from 0.0 to 0.1
  # In case of any breaking changes, bump the majore version, update from 0.0 to 1.0
  MODEL_PAYLOAD_VERSION = {
    'Account' => '1.2',
    'Helpdesk::Ticket' => '2.10',
    'Helpdesk::Note' => '0.6',
    'Solution::Category' => '0.1',
    'Solution::Folder' => '0.1',
    'Solution::Article' => '0.1',
    'Bot::FeedbackMapping' => '0.1',
    'User' => '0.2',
    'Company' => '1.2',
    'Subscription' => '1.2',
    'Agent' => '2.2',
    'VaRule' => '0.2',
    'Group' => '3.1',
    'Post' => '0.1',
    'Helpdesk::TimeSheet' => '1.2',
    'DashboardAnnouncement' => '0.1',
    'Social::TwitterHandle' => '0.1',
    'Social::TwitterStream' => '0.1',
    'Integrations::InstalledApplication' => '0.1',
    'Social::FacebookPage' => '0.3',
    'Product' => '0.1',    
    'Helpdesk::TicketField' => '1.1',
    'AgentGroup' => '0.1',
    'Helpdesk::Tag' => '0.1',
    'Helpdesk::TagUse' => '0.1',
    'Helpdesk::TicketStatus' => '0.1',
    'Helpdesk::PicklistValue' => '0.1',
    'Survey' => '0.1',
    'SurveyHandle' => '0.1',
    'SurveyResult' => '0.1',
    'CustomSurvey::Survey' => '0.1',
    'CustomSurvey::SurveyQuestion' => '0.1',
    'CustomSurvey::SurveyQuestionChoice' => '0.1',
    'CustomSurvey::SurveyHandle' => '0.1',
    'CustomSurvey::SurveyResult' => '0.1',
    'ContactField' => '0.1',
    'ContactFieldChoice' => '0.1',
    'CompanyField' => '0.1',
    'CompanyFieldChoice' => '0.1',
    'Freshcaller::Account' => '0.2',
    'Freshchat::Account' => '0.1',
    'Admin::CannedResponses::Folder' => '0.1',
    'Admin::CannedResponses::Response' => '0.1',
    'ConversionMetric' => '0.1',
    'Portal' => '0.1'
  }
end
