CREATE TABLE helpdesk_report_stats (received_tickets int NOT NULL DEFAULT '0' encode runlength,
resolved_tickets int NOT NULL DEFAULT '0' encode runlength,backlog_tickets  int NOT NULL DEFAULT '0' encode runlength,
avg_resp_time float DEFAULT NULL encode delta32k,avg_resp_time_by_bhrs float DEFAULT NULL encode bytedict,
first_responded_tickets int NOT NULL DEFAULT '0' encode runlength,
first_resp_time int DEFAULT NULL encode delta32k,first_resp_time_by_bhrs int DEFAULT NULL encode bytedict,
resolution_time int DEFAULT NULL encode delta32k,
resolution_time_by_bhrs int DEFAULT NULL encode bytedict,customer_interactions int NOT NULL DEFAULT '0' encode runlength,
agent_interactions int NOT NULL DEFAULT '0' encode runlength,num_of_reopens int NOT NULL DEFAULT '0' encode runlength,
assigned_tickets int NOT NULL DEFAULT '0' encode runlength,num_of_reassigns int NOT NULL DEFAULT '0' encode runlength,
fcr_tickets int NOT NULL DEFAULT '0' encode runlength,sla_tickets int NOT NULL DEFAULT '0' encode runlength,
happy_rated_tickets int NOT NULL DEFAULT '0' encode runlength,neutral_rated_tickets int NOT NULL DEFAULT '0' encode runlength,
unhappy_rated_tickets int NOT NULL DEFAULT '0' encode runlength,
ticket_type varchar(255) DEFAULT NULL encode runlength,priority int DEFAULT '1' encode bytedict,
source int DEFAULT '0' encode runlength,status int DEFAULT '0' encode bytedict,
account_id bigint DEFAULT NULL encode bytedict,requester_id bigint DEFAULT NULL encode delta32k,
responder_id bigint DEFAULT NULL encode bytedict,group_id bigint DEFAULT NULL encode bytedict,
product_id bigint DEFAULT NULL encode bytedict,survey_rating int DEFAULT NULL encode bytedict,
customer_id bigint DEFAULT NULL encode bytedict,
created_hour int DEFAULT NULL encode bytedict,resolved_hour int DEFAULT NULL encode bytedict,
created_at timestamp DEFAULT NULL encode bytedict distkey,
ffs_01 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_02 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_03 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_04 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_05 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_06 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_07 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_08 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_09 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_10 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode text255,
ffs_11 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_12 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_13 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_14 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_15 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_16 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_17 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_18 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_19 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_20 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_21 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_22 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_23 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_24 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_25 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_26 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_27 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_28 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_29 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength,
ffs_30 varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL encode runlength) SORTKEY(account_id, created_at);
