:independent_setup_keys:
  new_account: 0 
  account_admin_email: 1 
  agents: 2 
  support_email: 3 
  automation: 5 
  data_import: 6
:condition_based_setup_keys:
  twitter: 4
  freshfone_number: 8
  email_notification: 9
  reports: 10
  forums: 11
:non_checklist_keys:
  sample_dashboard: 12
  customize_domain: 13
  reply_to_ticket: 14
  welcome_video: 15
  team_inbox: 16
  canned_response: 17
  sample_data: 18

:onboarding_v2_keys:
  support_channel: 19
  manage_conversation_video: 20
  ticket_list_tour: 21
  explore_conversation_features: 22
  agent_productivity_video: 23
  canned_response_tour: 24
  explore_productivity_features: 25
  report_video: 26
  report_tour: 27
  explore_performance_feature: 28
  app_video: 29
  app_integration: 30
  explore_extend_capability_features: 31

:setup_keys_display_order:
  - new_account
  - account_admin_email
  - reply_to_ticket
  - customize_domain
  - support_email
  - agents
  - email_notification
  - freshfone_number
  - twitter
  - automation
  - data_import
  - reports
  - forums
  - sample_dashboard
  - welcome_video
  - team_inbox
  - canned_response
  - sample_data
  - support_channel
  - manage_conversation_video
  - ticket_list_tour
  - explore_conversation_features
  - agent_productivity_video
  - canned_response_tour
  - explore_productivity_features
  - report_video
  - report_tour
  - explore_performance_feature
  - app_video
  - app_integration
  - explore_extend_capability_features