:independent_setup_keys:
  new_account: 0 
  account_admin_email: 1 
  agents: 2 
  support_email: 3 
  automation: 5 
  data_import: 6 
  custom_app: 7
:condition_based_setup_keys:
  twitter: 4
  freshfone_number: 8 
:setup_keys_display_order:
  - new_account
  - account_admin_email
  - agents
  - support_email
  - freshfone_number
  - twitter
  - automation
  - data_import
  - custom_app
