:independent_setup_keys:
  new_account: 0 
  account_admin_email: 1 
  agents: 2 
  support_email: 3 
  automation: 5 
  data_import: 6
  setup_chat_channel: 66
  setup_caller_channel: 67
  choose_channel: 68
  explore_support_channels: 69
:condition_based_setup_keys:
  twitter: 4
  custom_app: 7
  freshfone_number: 8
  email_notification: 9
  reports: 10
  forums: 11
:non_checklist_keys:
  sample_dashboard: 12
  customize_domain: 13
  reply_to_ticket: 14
  welcome_video: 15
  team_inbox: 16
  canned_response: 17
  sample_data: 18

:onboarding_v2_keys:
  support_channel: 19
  manage_conversation_video: 20
  ticket_list_tour: 21
  explore_conversation_features: 22
  agent_productivity_video: 23
  canned_response_tour: 24
  explore_productivity_features: 25
  analytics_video: 26
  canned_analytics_tour: 27
  explore_performance_feature: 28
  app_video: 29
  app_integration: 30
  explore_extend_capability_features: 31
  tickets_intro: 32
  support_efficiently: 33
  integration_tour: 34
  bench_mark_customer: 35
  custom_apps: 36
  awesome_ticket_features: 37
  omni_support: 38
  explore_channels: 39
  automate_redundancy: 40
  csat_tour: 41
  never_lose_ticket_track: 42
  analytics_tour: 43
  intelligent_automation: 44
  self_service: 45
  answer_bot: 46
  strengthen_self_service: 47
  analytics_overview: 48
  curated_reports: 49
  marketplace: 50
  setup_support_email_video: 51
  ticketdetail_tour: 52
  sla_tour: 53
  automation_tour: 54
  slareminder_tour: 55
  faq_tour: 56
  overview_fsm_video: 57
  explore_fsm_features: 58
  update_account: 65
  integrate_freshsales: 71
  unify_beneficial_video: 72
:onboarding_goals:
  organiseand_keep_track: 59
  unify_support_channels: 60
  automate_repetitive_tasks: 61
  offer_self_service: 62
  track_agents_performance: 63
  integrate_with_apps: 64
  manage_field_workforce: 70
:freshmarketer_events:
  fdesk_tickets_view: 71
  fdesk_sla: 72
  fdesk_automation: 73
  fdesk_self_service: 74
  fdesk_ticket_assignment: 75
  fdesk_analytics: 76
  fdesk_apps: 77
  fdesk_add_agents: 78

:onboarding_v2_goals:
  - organiseand_keep_track
  - unify_support_channels
  - automate_repetitive_tasks
  - offer_self_service
  - track_agents_performance
  - integrate_with_apps
  - manage_field_workforce

:setup_keys_display_order:
  - unify_beneficial_video
  - integrate_freshsales
  - new_account
  - account_admin_email
  - reply_to_ticket
  - update_account
  - customize_domain
  - support_email
  - custom_app
  - agents
  - email_notification
  - freshfone_number
  - twitter
  - automation
  - data_import
  - reports
  - forums
  - sample_dashboard
  - welcome_video
  - team_inbox
  - canned_response
  - sample_data
  - support_channel
  - manage_conversation_video
  - ticket_list_tour
  - explore_conversation_features
  - agent_productivity_video
  - canned_response_tour
  - explore_productivity_features
  - analytics_video
  - canned_analytics_tour
  - explore_performance_feature
  - app_video
  - app_integration
  - explore_extend_capability_features
  - tickets_intro
  - support_efficiently
  - bench_mark_customer
  - awesome_ticket_features
  - omni_support
  - explore_channels
  - automate_redundancy
  - never_lose_ticket_track
  - intelligent_automation
  - self_service
  - answer_bot
  - strengthen_self_service
  - analytics_overview
  - curated_reports
  - marketplace
  - setup_support_email_video
  - ticketdetail_tour
  - sla_tour
  - automation_tour
  - slareminder_tour
  - faq_tour
  - csat_tour
  - analytics_tour
  - integration_tour
  - custom_apps
  - overview_fsm_video
  - explore_fsm_features
  - setup_chat_channel
  - setup_caller_channel
  - choose_channel
  - explore_support_channels