:independent_setup_keys:
  new_account: 0 
  account_admin_email: 1 
  agents: 2 
  support_email: 3 
  automation: 5 
  data_import: 6
:condition_based_setup_keys:
  twitter: 4
  custom_app: 7
  freshfone_number: 8
  email_notification: 9
  reports: 10
  forums: 11
:non_checklist_keys:
  sample_dashboard: 12
  customize_domain: 13
  reply_to_ticket: 14
  welcome_video: 15
  team_inbox: 16
  canned_response: 17
  sample_data: 18

:setup_keys_display_order:
  - new_account
  - account_admin_email
  - reply_to_ticket
  - customize_domain
  - support_email
  - custom_app
  - agents
  - email_notification
  - freshfone_number
  - twitter
  - automation
  - data_import
  - reports
  - forums
  - sample_dashboard
  - welcome_video
  - team_inbox
  - canned_response
  - sample_data