defaults: &defaults
  cache: false
  protect: true

development:
  <<: *defaults

test:
  <<: *defaults
  protect: false

staging:
  <<: *defaults
  cache: true

production:
  <<: *defaults
  cache: true
