Agent Collision: 
  - :agent_collision
Chat:
  - :chat
  - :chat_enable
Custom Roles: 
  - :custom_roles
Custom Ssl: 
  - :custom_domain
  - :custom_ssl
Enterprise Reporting:
  - :enterprise_reporting
  - :surveys
  - :survey_links
  - :timesheets
Gamification:
  - :forums
  - :gamification
  - :gamification_enable
  - :surveys
  - :survey_links
Multiple Business Hours: 
  - :multiple_business_hours
Layout Customization:
  - :css_customization
  - :forums
  - :layout_customization
  - :surveys
  - :survey_links
Round Robin:
  - :round_robin
