Agent Collision: 
  - :collision
Chat:
  - :chat
  - :chat_enable
Chat Routing:
  - :chat_routing
Custom Domain:
  - :custom_domain
Custom Mailbox:
  - :mailbox
Custom Roles: 
  - :custom_roles
Custom Slas:
  - :customer_slas
Custom Ssl: 
  - :custom_domain
  - :custom_ssl
Dynamic Sections:
  - :dynamic_sections
  - :multi_dynamic_sections
Enterprise Reporting:
  - :enterprise_reporting
  - :surveys
  - :survey_links
  - :timesheets
  - :auto_ticket_export
  - :ticket_activity_export
Gamification:
  - :forums
  - :gamification
  - :gamification_enable
  - :surveys
  - :survey_links
Multiple Business Hours: 
  - :multiple_business_hours
Layout Customization:
  - :css_customization
  - :forums
  - :layout_customization
  - :surveys
  - :survey_links
Round Robin:
  - :round_robin
  - :round_robin_on_update
Whitelisted Ips:
  - :whitelisted_ips
Custom Surveys:
  - :custom_surveys
Call Center Advanced:
  - :freshfone_call_metrics
  - :freshfone_call_monitoring
  - :freshfone_caller_id_masking
  - :agent_conference
  - :freshfone_warm_transfer
Helpdesk Restriction:
  - :helpdesk_restriction_toggle
Ticket Templates:
  - :ticket_templates
Round Robin Load Balancing:
  - :round_robin_load_balancing
Parent Child Tickets:
  - :parent_child_tickets_toggle
Link Tickets:
  - :link_tickets_toggle
Shared Ownership:
  - :shared_ownership_toggle
Skill Based Round Robin:
  - :skill_based_round_robin