Agent Collision: 
  - :collision
Chat:
  - :chat
  - :chat_enable
Chat Routing:
  - :chat_routing
Custom Domain:
  - :custom_domain
Custom Mailbox:
  - :mailbox
Custom Roles: 
  - :custom_roles
Custom Slas:
  - :customer_slas
Custom Slas 19:
  - :customer_slas
Custom Ssl: 
  - :custom_domain
  - :custom_ssl
Custom Ssl 19:
  - :custom_domain
  - :custom_ssl
Dynamic Sections:
  - :dynamic_sections
One Contact Multiple Companies:
  - :multiple_user_companies
  - :multiple_companies_toggle
One Contact Multiple Companies 19:
  - :multiple_user_companies
  - :multiple_companies_toggle
Enterprise Reporting:
  - :enterprise_reporting
  - :surveys
  - :survey_links
  - :timesheets
  - :auto_ticket_export
  - :ticket_activity_export
Enterprise Reporting 19:
  - :enterprise_reporting
  - :surveys
  - :survey_links
  - :timesheets
  - :auto_ticket_export
  - :ticket_activity_export
Gamification:
  - :forums
  - :gamification
  - :gamification_enable
  - :surveys
  - :survey_links
Multiple Business Hours: 
  - :multiple_business_hours
Layout Customization:
  - :css_customization
  - :forums
  - :layout_customization
  - :surveys
  - :survey_links
Round Robin:
  - :round_robin
  - :round_robin_on_update
Whitelisted Ips:
  - :whitelisted_ips
Whitelisted Ips 19:
  - :whitelisted_ips
Custom Surveys:
  - :custom_surveys
Call Center Advanced:
  - :freshfone_call_metrics
  - :freshfone_call_monitoring
  - :freshfone_caller_id_masking
  - :agent_conference
  - :freshfone_warm_transfer
Unique External Id:
  - :unique_contact_identifier
Unique External Id 19:
  - :unique_contact_identifier
Helpdesk Restriction:
  - :helpdesk_restriction_toggle
Ticket Templates:
  - :ticket_templates
Round Robin Load Balancing:
  - :round_robin_load_balancing
Parent Child Tickets:
  - :parent_child_tickets_toggle
Link Tickets:
  - :link_tickets_toggle
Shared Ownership:
  - :shared_ownership_toggle
Skill Based Round Robin:
  - :skill_based_round_robin
Sandbox:
  - :sandbox
Sandbox 19:
  - :sandbox
Field Service Management:
  - :field_service_management
Fluffy Forest:
  - :fluffy_forest
Fluffy Higher Plan1:
  - :fluffy_higher_plan1
Fluffy Higher Plan2:
  - :fluffy_higher_plan2 
Fluffy Higher Plan3:
  - :fluffy_higher_plan3 
Fluffy Higher Plan4:
  - :fluffy_higher_plan4 
Custom Slas 20:
  - :customer_slas
Fluffy Forest 20:
  - :fluffy_forest
Fluffy Higher Plan1 20:
  - :fluffy_higher_plan1
Fluffy Higher Plan2 20:
  - :fluffy_higher_plan2 
Fluffy Higher Plan3 20:
  - :fluffy_higher_plan3 
Fluffy Higher Plan4 20:
  - :fluffy_higher_plan4
Unique External Id 20:
  - :unique_contact_identifier
Whitelisted Ips 20:
  - :whitelisted_ips
One Contact Multiple Companies 20:
  - :multiple_user_companies
  - :multiple_companies_toggle
Custom Ssl 20:
  - :custom_domain
  - :custom_ssl
Field Service Management 20:
  - :field_service_management
Freddy Ultimate:
  - :agent_assist_ultimate
Detect Thankyou Note Migration:
  - :detect_thank_you_note
  - :detect_thank_you_note_eligible
Smart Filter Migration:
  - :smart_filter
Sla Management Migration:
  - :sla_management
Customer slas Migration:
  - :customer_slas
Audit Log UI And Multi Product Migration:
  - :audit_log_ui
  - :audit_logs_central_publish
  - :unlimited_multi_product
Article Versioning Migration:
  - :article_versioning
Whitelisted Ips Migration:
  - :whitelisted_ips
Skill Based Round Robin Migration:
  - :skill_based_round_robin
Sandbox Migration:
  - :sandbox
Hipaa Migration:
  - :hipaa
Article Approval Workflow Migration:
  - :article_approval_workflow
Agent Assist Lite Migration:
  - :agent_assist_lite
Autofaq Migration:
  - :autofaq
Botflow Migration:
  - :botflow
Emailbot Migration:
  - :emailbot
Custom Objects Migration:
  - :custom_objects
Agent Articles Suggest Migration:
  - :agent_articles_suggest_eligible
