common: &common

development:
 account_url: localhost:3000
 shared_secret: 

staging:
 account_url: 
 shared_secret: 

production:
 account_url: 
 shared_secret: 

testing:
 account_url: 
 shared_secret:   