defaults: &defaults
  api_path: "/api/code_console_api/code_execution_result"
  code_console_file_path: "supreme/code_console/code_results/code_snippet_log_"

development:
  <<: *defaults
  domain: "admin.freshdesk-dev.com:3001"

staging:
  <<: *defaults
  domain: "supreme.freshpo.com"

production:
  <<: *defaults
  domain: "supreme.freshdesk.com"

test:
  <<: *defaults