default: &default
  path: /v1/kvm
  api_key: dummy
  clear_cache_path: /fetch_domain_info
  update_kvm_path: /update_domain_info
  s3_bucket_name: dummy
  s3_file_name: apigee_domains_file.txt
  url: dummy

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
