:development: 
  :dynamo: 
    :endpoint: https://localhost:4569
    :access_key_id: dummy
    :secret_access_key: dummy
    :region: 'us-east-1'
  :sqs: 
    :endpoint: https://localhost:4576
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'
  :s3:
    :endpoint: https://localhost:4572
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'
  :route53:
    :endpoint: https://localhost:4572
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'
:test:
  :dynamo: 
    :endpoint: https://localhost:4569
    :access_key_id: dummy
    :secret_access_key: dummy
    :region: 'us-east-1'
  :sqs: 
    :endpoint: https://localhost:4576
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'
  :s3:
    :endpoint: https://localhost:4572
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'
  :route53:
    :endpoint: https://localhost:4572
    :access_key_id: dummy
    :secret_access_key: dummy
    :ssl_verify_peer: false
    :region: 'us-east-1'  

