--- 
:development: 
  :dynamo: 
    :endpoint: http://localhost:4569
    :access_key_id: dummy
    :secret_access_key: dummy
  :sqs: 
    :endpoint: http://localhost:4568
    :access_key_id: dummy
    :secret_access_key: dummy
:test:
  :dynamo: 
    :endpoint: http://localhost:4569
    :access_key_id: dummy
    :secret_access_key: dummy
  :sqs: 
    :endpoint: http://localhost:4568
    :access_key_id: dummy
    :secret_access_key: dummy
:staging:
  :dynamo: 
    :access_key_id: AKIAILZZJD6Q3WAFMCHA
    :secret_access_key: T8LomtbPUYQpVzcyDmcqkuHuScadfmeHh5t1Jv9Y
    :region: 'us-east-1'
  :sqs: 
    :access_key_id: AKIAILZZJD6Q3WAFMCHA
    :secret_access_key: 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
    :region: 'us-east-1'
