--- 
client_side_encryption_key: 
  development: MIIBCgKCAQEAwVsB14ppcSzurJvb0OAImD8vQ/8OJq5dVZO9/YvuqwWoG9VF1zO51M2pfsnHeo3jNis5pz/0Kw9FBQcloOpqLU8RfiWBjVfWYxJMyQIMh99XiqEB0FFoURjzgka0/x6/hYZefI988ZwQ7Ys4Ox3PlMfO35qyhZndbITs0XhDrd5ii8fs04HNPw+aAdDs0UF/5+ISKsslrMGLHFrcFqxU4wKefBiCc2o93hbxoKGZwILNfP5NHVYHgT8UMuXa7qdfJNuVlqP7qB+cyEZhjNdzfzjccZNyzHdjEhblHQUY0Dpm5E2RT/XGhIpGLSI3wF0DFEj59g+f/ri7OGuqONqHaQIDAQAB
  
