defaults: &defaults
  zapier:
    auth_type: jwt
    jwt_secret: 0222bcd8eb9911e7891d186590cc7ba7
    secret_key: 0fde22cebceca72d39b841bb72043941
    iv: c9e65436ee6218c7
  frankbot:
    auth_type: jwe
    secret_key: 0222bcd8eb9911e7891d186590cc7ba7
    jwt_secret: 0fde22cebceca72d39b841bb72043941
    jwt_default_expiry: 10000
  twitter:
    auth_type: jwt
    jwt_secret: 9rQ7H5RVm35vSvNUDWFjZPz3YKsqxp8p
  proactive:
    auth_type: jwt
    jwt_secret: abcdefgh12345678
  ocr_channel:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b11"]
    jwt_default_expiry: "30"
  freshmover:
    auth_type: jwt
    jwt_secret: c424bc33cae8d6fcab671a2f26161cc6
    jwt_default_expiry: "30"
development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
