defaults: &defaults
  zapier:
    auth_type: dummy
    jwt_secret: dummy
    secret_key: dummy
    iv: dummy
  frankbot:
    auth_type: dummy
    secret_key: dummy
    jwt_secret: dummy
    jwt_default_expiry: dummy

  freddy:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b12"]
    jwt_default_expiry: "30"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
