development:
  dedup_interval: 60
  hop_interval: 5
  schema_version: 1
  tenant: balaji-dev
  region: us-east-1
test:
  dedup_interval: 60
  hop_interval: 5
  schema_version: 1
  region: us-east-1
  tenant: development
staging:
  dedup_interval: 60
  hop_interval: 5
  schema_version: 1
  region: us-east-1
  tenant: development
production:
  dedup_interval: 60
  hop_interval: 5
  schema_version: 1
  region: us-east-1
  tenant: development