defaults: &defaults
  zapier:
    auth_type: jwt
    jwt_secret: 0222bcd8eb9911e7891d186590cc7ba7
    secret_key: 0fde22cebceca72d39b841bb72043941
    iv: c9e65436ee6218c7
  frankbot:
    auth_type: jwe
    secret_key: 0222bcd8eb9911e7891d186590cc7ba7
    jwt_secret: 0fde22cebceca72d39b841bb72043941
    jwt_default_expiry: 10000
  twitter:
    auth_type: jwt
    jwt_secret: 9rQ7H5RVm35vSvNUDWFjZPz3YKsqxp8p
  proactive:
    auth_type: jwt
    jwt_secret: abcdefgh12345678
  ocr_channel:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b11"]
    jwt_default_expiry: "30"
  freddy:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b12"]
    jwt_default_expiry: "30"
  freshchat:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b13"]
    jwt_default_expiry: "30"
  freshmover:
    auth_type: jwt
    jwt_secret: c424bc33cae8d6fcab671a2f26161cc6
    jwt_default_expiry: "30"
  freshconnect:
    auth_type: jwt
    jwt_secret: W1NtUgXBScTyild7gx4rBEpG_r_oWcK4XkC3N0xG40U=
    jwt_default_expiry: "30"
  sherlock:
    auth_type: jwt
    jwt_secret: b202ec2b19b12bde6d665e87962fc
  facebook:
    auth_type: jwt
    jwt_secret: 9rQ7H5RVm35vSvNUDWFjZPz3YKsqxp8p
  freshbots:
    auth_type: jwt
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b12"]
  twilight:
    auth_type: jwt
    jwt_secret: 34f6b896d197c09b0a2d90431da8257c
  field_service:
    auth_type: jwt
    jwt_secret: ix7T2vY2ZuQ8XGB7Uh0lJ4PiqJ4T7Gkj
  silkroad:
    auth_type: "jwt"
    jwt_secret: ["9rQ7H5RVm35vSvNUDWFjZPz3YKsqxp8z"]
  kbservice:
    auth_type: "jwt"
    jwt_secret: ["f94EEa09B3dde55964AB1793021154f0"]
  analytics:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b15"]
  freshdesk:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b16"]
  search:
    auth_type: "jwt"
    jwt_secret: ["0bc477b3c1df7c17be0999c247907b17"]

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
