defaults: &defaults
  key: "Chromehelpkit"
  iv: "1324659871023654"

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
