defaults: &defaults
  tcp_host: "172.16.20.158"
  tcp_port: "3310"
  connection_pool_size: 5
  timeout: 10
  socket_timeout : 15
development:
  <<: *defaults
  tcp_host: "127.0.0.1"
staging: 
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults