{
  "Automotive": {"name": "Automotive", "id": 2583},
  "Consumer Durables & Apparel": {"name": "Consumer Products", "id": 2605},
  "Diversified Consumer Services": {"name": "Service", "id": 2606},
  "Hotels, Restaurants & Leisure": {"name": "Hospitality", "id": 2600},
  "Consumer Goods": {"name": "Consumer Products", "id": 2605},
  "Household Durables": {"name": "Other", "id": 2560},
  "Leisure Products": {"name": "Entertainment & Leisure", "id": 2620},
  "Textiles, Apparel & Luxury Goods": {"name": "Apparel & Accessories", "id": 2581},
  "Education Services": {"name": "Education", "id": 2613},
  "Family Services": {"name": "Service", "id": 2606},
  "Specialized Consumer Services": {"name": "Service", "id": 2606},
  "Media": {"name": "Media", "id": 2563},
  "Distributors": {"name": "Shipping", "id": 2572},
  "Specialty Retail": {"name": "Retail & Wholesale", "id": 2602},
  "Beverages": {"name": "Food, Beverage & Tobacco", "id": 2626},
  "Food Products": {"name": "Food, Beverage & Tobacco", "id": 2626},
  "Food & Staples Retailing": {"name": "Food, Beverage & Tobacco", "id": 2626},
  "Personal Products": {"name": "Consumer Products", "id": 2605},
  "Tobacco": {"name": "Food, Beverage & Tobacco", "id": 2626},
  "Gas Utilities": {"name": "Energy", "id": 2618},
  "Banks": {"name": "Banking", "id": 2585},
  "Capital Markets": {"name": "Venture Capital", "id": 2625},
  "Diversified Financial Services": {"name": "Financial Services", "id": 2624},
  "Insurance": {"name": "Insurance", "id": 2564},
  "Real Estate": {"name": "Real Estate", "id": 2599},
  "Health Care Equipment & Supplies": {"name": "Health Care", "id": 2571},
  "Health Care Providers & Services": {"name": "Health Care", "id": 2571},
  "Biotechnology": {"name": "Biotechnology", "id": 2592},
  "Pharmaceuticals": {"name": "Pharmaceuticals", "id": 2593},
  "Professional Services": {"name": "Service", "id": 2606},
  "Aerospace & Defense": {"name": "Aerospace", "id": 2575},
  "Air Freight & Logistics": {"name": "Aircraft", "id": 2577},
  "Airlines": {"name": "Airline", "id": 2579},
  "Commercial Services & Supplies": {"name": "Service", "id": 2606},
  "Construction & Engineering": {"name": "Construction", "id": 2566},
  "Electrical Equipment": {"name": "Energy", "id": 2618},
  "Industrial Conglomerates": {"name": "Manufacturing", "id": 2580},
  "Machinery": {"name": "Machinery", "id": 2562},
  "Marine": {"name": "Other", "id": 2560},
  "Road & Rail": {"name": "Transportation", "id": 2621},
  "Trading Companies & Distributors": {"name": "Brokerage", "id": 2590},
  "Transportation": {"name": "Transportation", "id": 2621},
  "Internet Software & Services": {"name": "Computer", "id": 2601},
  "IT Services": {"name": "Computer", "id": 2601},
  "Software": {"name": "Computer", "id": 2601},
  "Communications Equipment": {"name": "Telecommunications", "id": 2617},
  "Electronic Equipment, Instruments & Components": {"name": "Electronics", "id": 2615},
  "Technology Hardware, Storage & Peripherals": {"name": "Technology", "id": 2614},
  "Building Materials": {"name": "Construction", "id": 2566},
  "Chemicals": {"name": "Chemicals", "id": 2598},
  "Containers & Packaging": {"name": "Cargo Handling", "id": 2596},
  "Metals & Mining": {"name": "Manufacturing", "id": 2580},
  "Paper & Forest Products": {"name": "Other", "id": 2560},
  "Diversified Telecommunication Services": {"name": "Telecommunications", "id": 2617},
  "Wireless Telecommunication Services": {"name": "Telecommunications", "id": 2617},
  "Renewable Electricity": {"name": "Energy", "id": 2618},
  "Electric Utilities": {"name": "Energy", "id": 2618},
  "Utilities": {"name": "Utilities", "id": 2567}
}