defaults: &defaults
  servers:
    - localhost:11211
  namespace: helpkit
  compress: true
  socket_max_failures: 2
  failover: false
  down_retry_delay: 10

development:
  <<: *defaults
slave:
  <<: *defaults
test:
  <<: *defaults
  namespace: helpkit_test
staging:
  <<: *defaults
