# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  encoding: utf8
  database: helpkit1
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  reconnect: true
  semian:
    enable: false
    success_threshold: 3
    error_threshold: 3
    error_timeout: 20
    bulkhead: false
    dryrun: false
  shards:
    shard_1:
      host: 127.0.0.1
      database: helpkit1
      not_a_shard: false
      semian:
        enable: false
        success_threshold: 3
        error_threshold: 3
        error_timeout: 20
        bulkhead: false
        dryrun: false
    sandbox_shard_1:
      host: 127.0.0.1
      database: helpkit2
      not_a_shard: false
      semian:
        enable: false
        success_threshold: 3
        error_threshold: 3
        error_timeout: 20
        bulkhead: false
        dryrun: false


# development:
#   adapter: mysql
#   encoding: utf8
#   database: helpkit1
#   username: root
#   password:

staging:
  adapter: mysql2
  encoding: utf8
  database: helpkit1
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  reconnect: true
  semian:
    enable: false
    success_threshold: 3
    error_threshold: 3
    error_timeout: 20
    bulkhead: false
    dryrun: false
  shards:
    shard_1:
      host: 127.0.0.1
      database: helpkit1
      not_a_shard: false
      semian:
        enable: false
        success_threshold: 3
        error_threshold: 3
        error_timeout: 20
        bulkhead: false
        dryrun: false

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  # adapter: sqlite3
  # database: db/test.sqlite3
  # timeout: 5000
  adapter: mysql2
  encoding: utf8
  database: helpkit_test_rails3
  host: 127.0.0.1
  username: root
  password:
  reconnect: true
  semian:
    enable: false
    success_threshold: 3
    error_threshold: 3
    error_timeout: 20
    bulkhead: false
    dryrun: false
  shards:
    shard_1: &test_shard
      host: 127.0.0.1
      database: helpkit_test_rails3
      not_a_shard: false
      semian:
        enable: false
        success_threshold: 3
        error_threshold: 3
        error_timeout: 20
        bulkhead: false
        dryrun: false
    sandbox_shard_1: &test_sandbox
      host: 127.0.0.1
      database: sandbox_test
      not_a_shard: false
      semian:
        enable: false
        success_threshold: 3
        error_threshold: 3
        error_timeout: 20
        bulkhead: false
        dryrun: false
test_new:
  <<: *test
  database: helpkit_test_new_rails3
  shards:
    shard_1:
      <<: *test_shard
      database: helpkit_test_new_rails3
    sandbox_shard_1:
      <<: *test_sandbox
      database: sandbox_test_new
production:
  adapter: sqlite3
  database: db/production.sqlite3
  timeout: 5000
