default_forum:
  - category: Announcements
    data: 0
    email: joe.mathew@freshdesk.com
    name: Joe Mathew
    views: 10
    likes: 5
    sticky: true
  - category: Announcements
    data: 1
    email: sam.kart@freshdesk.com
    name: Sam Kart
    views: 6
    likes: 3
    sticky: false
    replies:
      - data: 0
        email: bob.tree@freshdesk.com
        name: Bob Tree
        address: 7, Stone Hill, W 240 St, NY
        phone: (829)-570-1297
      - data: 1
        email: aroundtheworld80@freshdesk.com
        name: Phileas Fogg
      - data: 2
        email: johnny.appleseed@freshdesk.com
        name: Johnny Appleseed
        address: 140, Sinclair St, Brooklyn Heights
        phone: (123)-412-834
  - category: Feature requests
    data: 2
    email: lewis.clarke@freshdesk.com
    name: Lewis Clarke
    views: 7
    likes: 8
    sticky: true
    status: 1
  - category: Feature requests
    data: 3
    email: soundofmusic@freshdesk.com
    name: Maria Von Trapp
    views: 14
    likes: 4
    sticky: false
    status: 2
    replies:
      - data: 0
        email:  matt.rogers@freshdesk.com
        name: Matt Rogers
      - data: 1
        email: sam.kart@freshdesk.com
        name: Sam Kart
  - category: Sales and offers
    data: 4
    email: sam.kart@freshdesk.com
    name: Sam Kart
    views: 10
    likes: 4
    sticky: false
    replies:
      - data: 0
        email: lewis.clarke@freshdesk.com
        name: Lewis Clarke
      - data: 1
        email: emily.dean@freshdesk.com
        name: Emily Dean
        address: 25, Sispal Street, Upper east side, Manhattan
        phone: (257)-715-491
  - category: Sales and offers
    data: 5
    email: joe.mathew@freshdesk.com
    name: Joe Mathew
    views: 15
    likes: 10
    sticky: true
    replies:
      - data: 0
        email: clboone@freshdesk.com
        name: Clarice Boone
  - category: Report a problem
    data: 6
    email: finchhoot1@freshdesk.com
    name: Finch Hoot
    views: 3
    likes: 0
    sticky: false
    replies:
      - data: 0
        email: sam.kart@freshdesk.com
        name: Sam Kart
  - category: Report a problem
    data: 7
    email: mark.colbert@freshdesk.com
    name: Mark Colbert
    views: 3
    likes: 0
    sticky: false
    replies:
      - data: 0
        email: joe.mathew@freshdesk.com
        name: Joe Mathew
industry_mapping:
  "Hotels, Restaurants & Leisure": travel
  "Internet Software & Services": "software & services"
  "Software": "software & services"
  "IT Services": "software & services"
  "Professional Services": "software & services"
default_ticket:
  base_tickets:
    - status: Open
      priority: high
      source: email
      type: Question
      group: Billing
      requester:
        info:
          name: James Dean
          email: james@freshdesk.com
    - status: Closed
      priority: high
      source: email
      type: Question
      requester:
        info:
          name: Rachel Doe
          email: rachel@freshdesk.com
          phone: 1 866 832 3090
        company:
          name: Acme Inc.
          domains: acmecorp.com
          account_tier: "Basic"
      responder: true
      survey: true
      replies:
        - content: 0
    - status: Open
      priority: low
      source: feedback_widget
      type: Question
      requester:
        info:
          name: Matt Rogers
          email: matt.rogers@freshdesk.com
      replies:
        - content: 0
    - status: Open
      priority: urgent
      source: email
      type: Refunds and Returns
      requester:
        info:
          name: Bob Tree
          email: bob.tree@freshdesk.com
      replies:
        - content: 0
    - status: Pending
      priority: high
      source: email
      type: Refunds and Returns
      requester:
        info:
          name: Polly
          email: polly@freshdesk.com
      replies:
        - content: 0 
          private: 1
    - status: Open
      priority: medium
      source: email
      type: Bulk orders
      requester:
        info:
          name: John
          email: john@freshdesk.com
    - status: Open
      priority: low
      source: email
      type: Refunds and Returns
      requester:
        info:
          name: Matt Rogers
          email: matt.rogers@freshdesk.com
  ecommerce:
    - status: open
      priority: medium
      source: email
      type: Question
      tags: shipping_address
      requester:
        info:
          name: Anne Richard
          email: anne.richard1@freshdesk.com
          phone: 1 869 673 5678
      group: Shipping and delivery
      survey: true
      replies:
        - content: 0
        - content: 1
          requester:
            info:
              name: Anne Richard
              email: anne.richard1@freshdesk.com
    - status: open
      priority: urgent
      source: email
      type: Problem
      tags: replacement
      group: Replacements
      requester:
        info:
          name: Matt Rogers
          email: matt.rogers@freshdesk.com
          phone: 1 789 563 3670
      replies:
        - content: 0
        - content: 1
          requester:
            info:
              name: Matt Rogers
              email: matt.rogers@freshdesk.com
    - status: open
      priority: medium
      source: email
      type: Question
      tags: address_change
      group: Account managers
      requester:
        info:
          name: Clarice Boone
          email: clboone@freshdesk.com
          phone: 896 5668 9780
      replies:
        - content: 0
    - status: open
      priority: medium
      source: email
      type: Question
      tags: payment_option
      requester:
        info:
          name: Phileas Fogg
          email: aroundtheworld80@freshdesk.com
      replies:
        - content: 0
  "software & services":
    - status: Pending
      priority: low
      source: email
      type: incident
      requester:
        info:
          name: Clarice Boone
          email: clboone@freshdesk.com
      group: Customer Support
      replies:
        - content: 0
    - status: Closed
      priority: high
      source: email
      type: Problem
      tags: login
      requester:
        info:
          name: Sam Osborne
          email: sam.ozzy@freshdesk.com
      group: Login and security
      survey: true
      replies:
        - content: 0
        - content: 1
          requester:
            info:
              name: Sam Osborne
              email: sam.ozzy@freshdesk.com
    - status: Pending
      priority: High
      source: email
      type: Request
      tags: storage
      requester:
        info:
          name: Rachel Zane
          email: rachel@freshdesk.com
      group: Development
      replies:
        - content: 0
    - status: Pending
      priority: urgent 
      source: email
      type: Question
      tags: cancel_account
      requester:
        info:
          name: Bob Tree
          email: bob.tree@freshdesk.com
      group: Account managers
      replies:
        - content: 0
  travel:
    - status: Pending
      priority: high
      source: email
      type: Cancellation
      tags: cancellation,refund
      requester:
        info:
          name: Mark Colbert
          email: mark.colbert@freshdesk.com
          phone: 1-444-444-4444
      group: Cancellation
      replies:
        - content: 0
        - content: 1
          requester:
            info:
              name: Mark Colbert
              email: mark.colbert@freshdesk.com
    - status: Resolved
      priority: high
      source: email
      type: Question
      tags: Baggage
      requester:
        info:
          name: Sam Kart
          email: samk@freshdesk.com
          phone: 1 869 673 5678
      group: Baggage
      survey: true
      replies:
          - content: 0
          - content: 1
            requester:
              info:
                name: Sam Kart
                email: samk@freshdesk.com
    - status: Pending
      priority: low
      source: email
      type: Question
      tags: cancellation,refund
      requester:
        info:
          name: Lewis Clarke
          email: lewis.clarke@freshdesk.com
          phone: 1 889 533 0357
      group: Cancellation
      replies:
        - content: 0
    - status: "Waiting on Third Party"
      priority: medium
      source: email
      type: Question
      tags: package_caribbean
      requester:
        info:
          name: Sara James
          email: sara.james@freshdesk.com
          phone: 896 5668 9780
      group: Marketing
      replies:
          - content: 0
  fsm_base_tickets:
    - status: Open
      priority: medium
      source: email
      type: Problem
      group: Account managers
      requester:
        info:
          name: Bob Tree
          email: bob.tree@freshdesk.com
      replies:
        - content: 0
      service_task:
        - status: Open
          priority: high
          type: Service Task
          group: Manhattan technicians
          contact:
            name: Bob Tree
            phone_number: (829)-570-1297
            service_location: 7, Stone Hill, W 240 St, NY
          appointment_start_time:
            day: 3
            hour: 14
            minute: 00
          appointment_end_time:
            day: 3
            hour: 15
            minute: 00
    - status: Open
      priority: high
      source: email
      type: Incident
      group: Escalations
      requester:
        info:
          name: Emily Dean
          email: emily.dean@freshdesk.com
      replies:
        - content: 0
      service_task:
        - status: Open
          priority: high
          type: Service Task
          group: Manhattan technicians
          contact:
            name: Emily Dean
            phone_number: (257)-715-491
            service_location: 25, Sispal Street, Upper east side, Manhattan
          appointment_start_time:
            day: 2
            hour: 10
            minute: 00
          appointment_end_time:
            day: 2
            hour: 11
            minute: 30
    - status: Open
      priority: high
      source: email
      type: Problem
      group: Account managers
      requester:
        info:
          name: Johnny Appleseed
          email: johnny.appleseed@freshdesk.com
      replies:
        - content: 0
      service_task:
        - status: Open
          priority: high
          type: Service Task
          group: Brooklyn Technicians
          contact:
            name: Johnny Appleseed
            phone_number: (123)-412-834
            service_location: 140, Sinclair St, Brooklyn Heights
          appointment_start_time:
            day: 3
            hour: 11
            minute: 00
          appointment_end_time:
            day: 3
            hour: 13
            minute: 00
