development:
  feeds:
    suffix: dev
    start_read_capacity: 2
    final_read_capacity: 10
    write_capacity: 5
  interactions:
    suffix: dev
    start_read_capacity: 2
    final_read_capacity: 10
    write_capacity: 5


staging:
  feeds:
    suffix: staging
    start_read_capacity: 10
    final_read_capacity: 10
    write_capacity: 5
  interactions:
    suffix: staging
    start_read_capacity: 10
    final_read_capacity: 10
    write_capacity: 5


production:
  feeds:
    suffix: production
    start_read_capacity: 10
    final_read_capacity: 20
    write_capacity: 25
  interactions:
    suffix: production
    start_read_capacity: 10
    final_read_capacity: 20
    write_capacity: 25


test:
  feeds:
    suffix: dev
    start_read_capacity: 10
    final_read_capacity: 10
    write_capacity: 5
  interactions:
    suffix: dev
    start_read_capacity: 10
    final_read_capacity: 10
    write_capacity: 5
