# Email settings for pop/imap fetching
incoming:
    defaults: &defaults
      type: imap
      server: imap.gmail.com
      port: 993
      ssl: true
      use_login: true
      username: support@freshdesk.com
      password: opmanager123
      processed_folder: fdver2m
    development:
      <<: *defaults
    test:
      type: pop
      server: localhost
      username: username
      password: password
    staging:
      <<: *defaults

# Email settings for sending mail
outgoing:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults
