# Email settings for pop/imap fetching
incoming:
    defaults: &defaults
      type: imap
      server: imap.gmail.com
      port: 993
      ssl: true
      use_login: true
      username: support@freshdesk.com
      password: opmanager123
      processed_folder: fdver2m
    development:
      <<: *defaults
    test:
      type: pop
      server: localhost
      username: username
      password: password
    staging:
      <<: *defaults

# Email settings for sending mail
outgoing:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-1:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-2:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-3:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-4:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-5:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-9:
    defaults: &defaults
      address: smtp.sendgrid.net
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: fdstage
      password: 45533keFi3c924T
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults 

category-11:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-12:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-13:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-14:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-15:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults

category-19:
    defaults: &defaults
      address: smtp.mailgun.org
      port: 587
      domain: freshpo.com
      authentication: :plain
      user_name: postmaster@trialmg.freshdesk.com
      password: e60abb3c5ee0060db5ed7ef0020bde7a
    development:
      <<: *defaults
    test:
      <<: *defaults
    staging:
      <<: *defaults
      
processing_timeout: 600
retry_count: 20
