defaults: &defaults
 app_id: 128260310615386
 secret_key: ab8eb7b00386bf05035b0c62031d43f3
 callback_url: http://login.freshbugs.com/social/facebook/authdone 


development:
 app_id: 282574098423372
 secret_key: f7f90af5765bf0b51f8346f97faac898
 callback_url: http://localhost.local:3000/social/facebook/authdone  

staging:
 app_id: 235038579942982
 secret_key: 13f90c9038dc120787bed4a29f9bea0f
 callback_url: http://login.freshbugs.com/social/facebook/authdone 

slave:
 <<: *defaults
test:
 <<: *defaults

production:
 app_id: 128260310615386
 secret_key: ab8eb7b00386bf05035b0c62031d43f3
 callback_url: http://login.freshdesk.com/social/facebook/authdone