:feature_description_keys:
    :skill_based_round_robin: skill_based_assignment_desc
    :sandbox: sandbox_desc
    :whitelisted_ips: whitelisted_ip_desc
    :omni_channel_routing: omni_routing
    :multi_product: multiple_products_desc
    :multiple_business_hours: multiple_sla_business_desc
    :portal_article_filters: portal_customization_desc
    :custom_ssl: custom_ssl_desc
    :round_robin: auto_ticket_assignment_desc
    :enterprise_reporting: enterprise_reports_desc
    :custom_dashboard: custom_dashboard_desc
    :botflow: chatbots
    :chat_routing: inapp_chat
    :field_service_management_toggle: fsm_desc
    :custom_translations: custom_translations
    :multi_language:  multilingual_kbase_desc
    :ticket_templates:  ticket_templates_desc
    :forums: forums_desc
    :analytics_agent_performance: agent_performance_report_desc
    :analytics_satisfaction_survey_report: satisfaction_survey_desc
    :custom_survey: custom_surveys_desc
    :custom_apps: custom_apps_desc
    :timesheets: timesheets_desc
    :autofaq: chat_faq
    :customer_journey: customer_journey_desc
    :mailbox: multiple_mailboxes_desc
    :custom_domain: custom_domain_desc
    :analytics_helpdesk_in_depth_report: helpdesk_report_desc
    :custom_ticket_fields: custom_ticket_fields_and_views_desc
    :collision: agent_collision_desc
    :dynamic_content: dynamic_email_alert_desc
    :analytics_report_schedule: scheduled_reports_desc
    :marketplace: app_gallery_desc
    :supervisor: time_event_automation_desc
    :sla_management: sla_reminders
