defaults: &defaults
  host: "localhost"
  username: "dummy"
  password: "dummy"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

slave:
  <<: *defaults
