# --------------------------------------------------------------------------- #
# Project Info
#   Defaults shown. Learn more about these options by running
#   `fontcustom help` or visiting <http://fontcustom.com>.
# --------------------------------------------------------------------------- #

font_name: glyphs
css_selector: .ficon-{{glyph}}
preprocessor_path: ""
autowidth: true
no_hash: false
force: true
debug: false
quiet: false


# --------------------------------------------------------------------------- #
# Input Paths
# --------------------------------------------------------------------------- #

input:
  vectors: public/glyphs/vectors         	# required
  templates: public/glyphs/templates


# --------------------------------------------------------------------------- #
# Output Paths
# --------------------------------------------------------------------------- #

output:
  fonts: public/assets                             # required
  css: public/src/fonts
  # preview: public/styleguide
  # freshdesk_preview.html: public/styleguide

# --------------------------------------------------------------------------- #
# Templates
#   Included in Font Custom: preview, css, scss, scss-rails
#   Custom templates should be saved in the INPUT[:templates] directory and
#   referenced by their baserame.
# --------------------------------------------------------------------------- #

templates:
 - scss
 # - preview
 - index.html
