defaults: &defaults
  freno_base_url: "http://freno.freshpo.com"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  freno_base_url: "http://freno.freshdesk.internal"
