defaults: &defaults
  subscription_host: 'http://localhost:8080/api/v1/billing'
  timeout: 10

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
