common: &common
  user_name: username
  password: password

development:
  Twitter:
    <<: *common
    rules_url: https://gnip-api.twitter.com/rules/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://gnip-stream.twitter.com/stream/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_stream_url: https://gnip-stream.gnip.com/replay/powertrack/accounts/Freshdesk/publishers/twitter/prod.json

staging:
  Twitter:
    <<: *common
    rules_url: https://gnip-api.twitter.com/rules/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://gnip-stream.twitter.com/stream/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_stream_url: https://gnip-stream.gnip.com/replay/powertrack/accounts/Freshdesk/publishers/twitter/prod.json

production:
  Twitter:
    <<: *common
    rules_url: https://gnip-api.twitter.com/rules/powertrack/accounts/Freshdesk/publishers/twitter/prod.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://gnip-stream.twitter.com/stream/powertrack/accounts/Freshdesk/publishers/twitter/prod.json
    replay_stream_url: https://gnip-stream.gnip.com/replay/powertrack/accounts/Freshdesk/publishers/twitter/prod.json

test:
  Twitter:
    <<: *common
    rules_url: https://gnip-api.twitter.com/rules/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://gnip-stream.twitter.com/stream/powertrack/accounts/Freshdesk/publishers/twitter/dev.json
    replay_stream_url: https://gnip-stream.gnip.com/replay/powertrack/accounts/Freshdesk/publishers/twitter/prod.json
