common: &common
  user_name: username
  password: password

development:
  Twitter:
    <<: *common
    rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev/rules.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev.json
    replay_stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod.json


staging:
  Twitter:
    <<: *common
    rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev/rules.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev.json
    replay_stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod.json


production:
  Twitter:
    <<: *common
    rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/prod/rules.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/prod.json
    replay_stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod.json

test:
  Twitter:
    <<: *common
    rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev/rules.json
    replay_rules_url: https://api.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod/rules.json
    stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/streams/track/dev.json
    replay_stream_url: https://stream.gnip.com:443/accounts/Freshdesk/publishers/twitter/replay/track/prod.json
