:competitor_keyword: 'compare-helpdesk'
:freshdesk_free_websites: 
  - 'free-ticketing'
  - 'free-helpdesk'
:sprout_trial_onboarding: 'sprout_trial_onboarding'
:freshdesk_signup: 'https://freshdesk.com/signup'
:freshdesk_brand_websites:
  - 'https://freshdesk.com'
  - 'https://freshdesk.com/pricing'
:personalised_onboarding_keywords: 
  - 'help'
  - 'ticket'
:onboarding_types: 
  - 'default_onboarding'
  - 'personalised_onboarding'