development:
  audit_log:
    api_endpoint: "http://hypertrail-dev.freshworksapi.com/api/v1/audit/account/%{account_id}"
    username: hypertrail-ci
    password: hypertrail-ci
test:
  audit_log:
    api_endpoint: "http://hypertrail-dev.freshworksapi.com/api/v1/audit/account/%{account_id}"
    username: hypertrail-ci
    password: hypertrail-ci
staging:
  audit_log:
    api_endpoint: "http://hypertrail-dev.freshworksapi.com/api/v1/audit/account/%{account_id}"
    username: hypertrail-ci
    password: hypertrail-ci
production:
  audit_log:
    api_endpoint: "http://hypertrail-dev.freshworksapi.com/api/v1/audit/account/%{account_id}"
    username: hypertrail-ci
    password: hypertrail-ci
