defaults: &defaults
  expiry: 300
  password: dummy
  kid: dummy
  client_secrets:
    field_service:
      client_id: field_service_dummy
      client_secret:
        - dummy
        - dummy

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

slave:
  <<: *defaults
