app:
  icontact:
    app_id: "qB7RYQgliAPwl5dwezYF0kAN4Islhj4e"
  xero:
    consumer_key: "GBCOF7ERX7TT1Y7ZHIFZR3UYH1R4WN"
    consumer_secret: "QSHJLDBPGOUO2PVT3I04OZUVHXXDI0"
  onedrive:
    client_id: "0000000044164F31"
    client_secret: "0aJhfYIgkDDPb-cE57TehreBwVlRKQd4"
  cloud_elements:
    development:
      auth_header: "User y31G0E60L6Zs/nZx7x0MJtRKCyhsJACUaAaDYU67S78=,Organization 3abb0215cd97f5f346f29a860e1e5982"
      crm_formula_template_id:
        salesforce_v2:  "4345"
        dynamics_v2: "5975"
      fd_formula_template_id:
        salesforce_v2: "4346"
        dynamics_v2: "5976"
    test:
      auth_header: "User y31G0E60L6Zs/nZx7x0MJtRKCyhsJACUaAaDYU67S78=,Organization 3abb0215cd97f5f346f29a860e1e5982"
      crm_formula_template_id:
        salesforce_v2:  "4345"
        dynamics_v2: "5975"
      fd_formula_template_id:
        salesforce_v2: "4346"
        dynamics_v2: "5976"
    staging:
      auth_header: "User HEr6MX+mVz+zMwfSRIydYpKVqSbI4F+LWhodHhj0IQk=,Organization e18df23b39be015812b0ae60911dccbd"
      crm_formula_template_id:
        salesforce_v2:  "5349"
        dynamics_v2: "6085"
      fd_formula_template_id:
        salesforce_v2: "5350"
        dynamics_v2: "6084"
    production:
      auth_header: "User 7ehqmCMXILFwqZN5z0PD0oZBFzK1paw3CMnfXF3Dtmc=,Organization 508a53340eac87879ff8e65ddfd39da0"
      crm_formula_template_id:
        salesforce_v2:  "3119"
      fd_formula_template_id:
        salesforce_v2: "3129"
marketplace_landing_paths:
  github: "/integrations/github/oauth_install"
  quickbooks: "/integrations/marketplace/quickbooks_sso/landing"
  shopify: "/integrations/marketplace/shopify/landing"
  google: "/integrations/marketplace/google/home"

api_keys:
  google_business_calendar: "AIzaSyCGPaSTHQRIbxBd-HVKJL510FSD4uVGHnU"

proxy_server:
  host: "127.0.0.1"
  port: 5050
  protocol: "http"