icontact:
 app_id: "qB7RYQgliAPwl5dwezYF0kAN4Islhj4e"
xero:
 consumer_key: "GBCOF7ERX7TT1Y7ZHIFZR3UYH1R4WN"
 consumer_secret: "QSHJLDBPGOUO2PVT3I04OZUVHXXDI0"
onedrive:
 client_id: "0000000044164F31"
 client_secret: "0aJhfYIgkDDPb-cE57TehreBwVlRKQd4" 