icontact:
 app_id: "qB7RYQgliAPwl5dwezYF0kAN4Islhj4e"
xero:
 consumer_key: "DNG4K32A9OTRBYEH4X2GGLY0UFCOJJ"
 consumer_secret: "QHZI3HGLARWOPQCBZFPQHMKPUHPENE"
onedrive:
 client_id: "0000000044164F31"
 client_secret: "0aJhfYIgkDDPb-cE57TehreBwVlRKQd4" 