--- 
ar: 1
ca: 2
cs: 3
da: 4
de: 5
en: 6
es-LA: 7
es: 8
et: 9
fi: 10
fr: 11
hu: 12
id: 13
it: 14
ja-JP: 15
ko: 16
nb-NO: 17
nl: 18
pl: 19
pt-BR: 20
pt-PT: 21
ru-RU: 22
sk: 23
sl: 24
sv-SE: 25
tr: 26
vi: 27
zh-CN: 28
