development: 
  auth_key: 7F77DC551CFF7BAB845879ABD41DA
  host: https://nba.freshpo.com
  sentiment_host: http://sentimentelb-866010645.us-east-1.elb.amazonaws.com
  method: post
  url: api/v1/suggest/tickets/
  predict_url: api/v1/predict/
  feedback_url: api/v1/feedback/
  timeout: 2
  ticket_count: 12
  kissmetrics: dd3a6b3aa13874947209d57df9ddca938d0ffe5c
production: 
  auth_key: 7F77DC551CFF7BAB845879ABD41DA
  host: https://nba.freshdesk.com
  sentiment_host: http://sentimentelb-866010645.us-east-1.elb.amazonaws.com
  method: post
  url: api/v1/suggest/tickets/
  predict_url: api/v1/predict/
  feedback_url: api/v1/feedback/
  timeout: 2
  ticket_count: 12
  kissmetrics: dd3a6b3aa13874947209d57df9ddca938d0ffe5c
staging: 
  auth_key: 7F77DC551CFF7BAB845879ABD41DA
  host: https://nba.freshpo.com
  sentiment_host: http://sentimentelb-866010645.us-east-1.elb.amazonaws.com
  method: post
  url: api/v1/suggest/tickets/
  predict_url: api/v1/predict/
  feedback_url: api/v1/feedback/
  timeout: 2
  ticket_count: 12
  kissmetrics: dd3a6b3aa13874947209d57df9ddca938d0ffe5c
test: 
  auth_key: 7F77DC551CFF7BAB845879ABD41DA
  host: https://nba.freshpo.com
  sentiment_host: http://sentimentelb-866010645.us-east-1.elb.amazonaws.com
  method: post
  url: api/v1/suggest/tickets/
  predict_url: api/v1/predict/
  feedback_url: api/v1/feedback/
  timeout: 2
  ticket_count: 12
  kissmetrics: dd3a6b3aa13874947209d57df9ddca938d0ffe5c