mobile_redirection_base_url : "https://freshdesk.page.link" 
android_app_bundle_id : "com.freshdesk.helpdesk"
ios_app_bundle_id : "com.freshdesk.helpdesk"
ios_app_store_id : "https://itunes.apple.com/in/app/freshdesk/id849713306"
playstore_store_url : "https://play.google.com/store/apps/details?id=com.freshdesk.helpdesk&hl=en_IN&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1"
app_store_url : "https://itunes.apple.com/in/app/freshdesk/id849713306?mt=8"