production:
  datetime: "http://ner.freshworksapi.com/datetime"
staging: 
  datetime: "http://ner.socialdev.io/datetime"
development: 
  datetime: "http://ner.socialdev.io/datetime"
test: 
  datetime: "http://ner.socialdev.io/datetime"
