defaults: &defaults
  api_endpoint: "http://localhost:3001/api/v1/"
  auth_type: "jwt"
  jwt_secret: "uRmMYCtGKITr4YCgouIqVicStGRs3SPo"
  jwt_default_expiry: "30"
  admin_jwt_secret: "admin-authkey"
  touchstone_secret: "647c69e8658c62379c0e42f04f36a61e"

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults