defaults: &defaults
  ocr_host: "http://localhost:9091/api/v1"
  ocr_key: "uRmMYCtGKITr4YCgouIqVicStGRs3SPo"
development:
  <<: *defaults
slave:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
