defaults: &defaults
  access_config:
    access_key_id: "AKIAJIKOIML4DS2K6GTQ"
    secret_access_key: "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"
  stack_details:
    stack_id: "931c141b-64fb-4e91-aa3a-b3a36c7c14e3"
    app_id: "abbe1238-d3d4-4192-832a-55c3816af61e"
  deploy_details:
    command:
      name: "deploy"
    comment: "Triggered from ey deployment"

development:
  <<: *defaults