--- 
:policies: 
  :minimum_characters: 0
  :cannot_contain_user_name: 1
  :cannot_be_same_as_past_passwords: 2
  :password_expiry: 3
  :session_expiry: 4
  :atleast_an_alphabet_and_number: 5
  :have_mixed_case: 6
  :have_special_character: 7
:max_value: 8

