# Used in account class to fill the pod info as part of shard_mapping
CURRENT_POD: poduseast # values can be poduseast, podeu. This should exactly match with the values of Nginx. Else routing may fail.

GLOBAL_POD: poduseast

CURRENT_REGION: "us-east-1"

pod_paths:
  pod_endpoint: "/fdadmin/freshops_pod/pod_endpoint"

access_key_id: ""
secret_access_key: ""
region: "us-east-1"

