common: &common
  feedback_path: api/channel/tickets
  contacts_path: api/v2/contacts
  tickets_path: api/v2/tickets

development:
  <<: *common
  api_key: dummy-api-key
  feedback_account: http://localhost.freshdesk-dev.com:3000
staging:
  <<: *common
  api_key: dummy-api-key
  feedback_account: https://feedback1.freshpo.com
production:
  <<: *common 
  api_key: dummy-api-key
  feedback_account: https://support.freshdesk.com
