:freshchat_plans:
  - 'Garden'
  - 'Estate'
  - 'Forest'
  - 'Garden Classic'
  - 'Estate Classic'
  - 'Premium'
  - 'Garden Jan 17'
  - 'Estate Jan 17'
  - 'Forest Jan 17'
  - 'Garden Jan 19'
  - 'Garden Omni Jan 19'
  - 'Estate Jan 19'
  - 'Estate Omni Jan 19'
  - 'Forest Jan 19'
  - 'Garden Jan 20'
  - 'Estate Jan 20'
  - 'Estate Omni Jan 20'
  - 'Forest Jan 20'
  - 'Forest Omni Jan 20'

:freshcaller_plan_mapping:
  sprout_jan_19: 'sprout'
  blossom_jan_19: 'sprout'
  garden_jan_19: 'blossom'
  garden_omni_jan_19: 'blossom'
  estate_jan_19: 'garden'
  estate_omni_jan_19: 'garden'
  forest_jan_19: 'estate'
  sprout_jan_20: 'Sprout 2020'
  blossom_jan_20: 'Blossom 2020'
  garden_jan_20: 'Garden 2020'
  estate_jan_20: 'Estate 2020'
  estate_omni_jan_20: 'Estate 2020'
  forest_jan_20: 'Forest 2020'
  forest_omni_jan_20: 'Forest 2020'

:freshchat_plan_mapping:
  sprout_jan_19: '1101'
  blossom_jan_19: '1101'
  garden_jan_19: '1201'
  garden_omni_jan_19: '1201'
  estate_jan_19: '1301'
  estate_omni_jan_19: '1301'
  forest_jan_19: '1401'
  sprout_jan_20: '2101'
  blossom_jan_20: '2201'
  garden_jan_20: '2301'
  estate_jan_20: '2401'
  estate_omni_jan_20: '2401'
  forest_jan_20: '2501'
  forest_omni_jan_20: '2501'
