defaults: &defaults
  connection_config:  
    host: localhost
    port: 5672
    username: guest
    password: guest
  secret_key: UIQX9K3VE716I1CB1X1DMB4EGL9963FP

development:
  <<: *defaults

test:
  <<: *defaults