random_s3_char:
 - ABCD
 - BCDE
 - CDEF
 - DEFG
 - EFGH
 - FGHI
 - GHIJ
 - HIJK
 - IJKL
 - JKLM
 - KLMN
 - LMNO
 - MNOP
 - NOPQ
 - OPQR
 - PQRS
 - QRST
 - RSTU
 - STUV
 - TUVW
 - UVWX
 - VWXY
 - WXYZ
 - XYZA
 - YZAB
 - ZABC
 - AEFG
 - BFGH
 - CGHI
 - DHIJ
 - EIJK
 - FJKL