"^/helpdesk/tickets/view/": "/a/tickets"
"^/helpdesk/tickets/filter/": "/a/tickets"
"^/admin/.+": "/a/admin/"
"^/solution/.+": "/a/solutions/"
"^/discussions/.+": "/a/forums/"
"^/social/.+": "/a/social/"
"^/reports.*": "/a/reports/"
"^/contacts/[0-9]+/.+": "/a/contacts/"
"^/contacts/filter.*": "/a/contacts/"
"^/companies/[0-9]+/.+": "/a/companies/"
"^/agents/.*": "/a/admin/"
"^/groups/[0-9]+/.+": "/a/admin/"
"^/support.*": "/a/"