defaults: &defaults
  app_id: dummy
  app_secret: dummy
  end_point: https://rts-staging.freshworksapi.com
  db_cipher_key: c6d28822fe84346e669d536edeab861dd61b2b2082b7
  channel_cipher_key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4
  jwt_default_expiry: 100
development:
  <<: *defaults
staging:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults