defaults: &defaults
  access_key_id: AKIAI4ZEO3SS3BAKANDQ
  secret_access_key: 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

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: AKIAJWGOEYKNTQ75K5TQ
  secret_access_key: 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

staging:
  <<: *defaults
