defaults: &defaults
  access_key_id: AKIAI4ZEO3SS3BAKANDQ
  secret_access_key: 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

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: AKIAI2ZN3QS4WSYRPLIQ
  secret_access_key: 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

staging:
  <<: *defaults
