defaults: &defaults
  access_key_id: AKIAI4ZEO3SS3BAKANDQ
  secret_access_key: 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

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: AKIAISZIJ5WPZKABHKSA
  secret_access_key: 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

staging:
  <<: *defaults
