defaults: &defaults
  access_key_id: dummy
  secret_access_key: dummy

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: dummy
  secret_access_key: dummy

staging:
  <<: *defaults
