defaults: &defaults
  access_key_id: AKIAI4ZEO3SS3BAKANDQ
  secret_access_key: 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

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: AKIAIJC5RAU5BFF3FQKA
  secret_access_key: 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

staging:
  <<: *defaults
