defaults: &defaults
  access_key_id: AKIAILZZJD6Q3WAFMCHA
  secret_access_key: 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

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

production:
  access_key_id: AKIAISZIJ5WPZKABHKSA
  secret_access_key: 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

staging:
  <<: *defaults
