defaults: &defaults
  poduseast: 'sandbox_shard_1'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  poduseast1: 'sandbox_shard_us'
  podeucentral1: 'sandbox_shard_euc'
  podapsoutheast2: 'sandbox_shard_au'
  podapsouth1: 'sandbox_shard_ind'
