common: &common
  end_point: http://scheduler-staging.freshworksapi.com/schedules
  token: 5d22173692589c423223f06307a0bdcb
  group_name: helpkit_test
  todo_group_name: helpkit_todo_reminder
  export_group_name: helpkit_export_cleanup
  ticket_delete_group_name: helpkit_ticket_delete
  downgrade_policy_group_name: helpkit_downgrade_policy_reminder
  account_cleanup_group_name: helpkit_suspended_account_cleanup
  monthly_to_annual_group_name: monthly_to_annual_notification
development:
  <<: *common
staging:
  <<: *common
test:
  <<: *common
production:
  <<: *common 