defaults: &defaults
  sendgrid:
    api:
      set_url: https://api.sendgrid.com/v3/user/webhooks/parse/settings
      get_specific_domain_url: https://api.sendgrid.com/v3/user/webhooks/parse/settings/
      delete_url: https://api.sendgrid.com/v3/user/webhooks/parse/settings/
      update_url: https://api.sendgrid.com/v3/user/webhooks/parse/settings/
    api_key: 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
    global_verification_key: 4a1beaedf946d6c4ea1b88567a
    dkim:
      key:
        sub_users:
          free-user: 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
          default-user: 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
        parent: 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
      configure: 
        timeout: 50
        retries: 10
        expire: 1
    timeout: 30
development:
  <<: *defaults
staging:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  
