aws:
  access_key_id: dummy
  secret_access_key: dummy
  region: us-east-1
  receive_message: # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
:verbose: true
:concurrency: 5
:logfile: ./log/shoryuken.log
:timeout: 30
:queues:
  - <%= SQS[:search_etl_queue] %>
  - <%= ES_V2_QUEUE_KEY % { cluster: 'cluster1' } %>
  - <%= ES_V2_QUEUE_KEY % { cluster: 'cluster1-archive' } %>
  - <%= SQS[:facebook_realtime_queue] %>
  - <%= SQS[:fb_message_realtime_queue] %>
  - <%= SQS[:count_etl_queue] %>
  - <%= SQS[:free_customer_email_queue] %>
  - <%= SQS[:trial_customer_email_queue] %>
  - <%= SQS[:active_customer_email_queue] %>
  - <%= SQS[:default_email_queue] %>
  - <%= SQS[:email_dead_letter_queue] %>
  - <%= SQS[:scheduled_ticket_export_complete] %>
  - <%= SQS[:scheduled_export_payload_enricher_queue] %>
  - <%= SQS[:channel_framework_services] %>
  - <%= SQS[:custom_mailbox_status] %>
  - <%= SQS[:bot_feedback_queue] %>
  - <%= SQS[:fd_scheduler_export_cleanup_queue] %>
