aws:
  access_key_id: dummy
  secret_access_key: dummy
  region: us-east-1
  sqs_endpoint: http://localhost:4568
:concurrency: 5
:logfile: ./log/shoryuken.log
:timeout: 30
:queues:
  - <%= SQS[:search_etl_queue] %>
  - <%= ES_V2_QUEUE_KEY % { cluster: 'cluster1' } %>
  - <%= SQS[:facebook_realtime_queue] %>
  - <%= SQS[:fb_message_realtime_queue] %>
  - <%= SQS[:count_etl_queue] %>
  - <%= SQS[:free_customer_email_queue] %>
  - <%= SQS[:trial_customer_email_queue] %>
  - <%= SQS[:active_customer_email_queue] %>
  - <%= SQS[:default_email_queue] %>
  - <%= SQS[:email_dead_letter_queue] %>
