:verbose: true
:concurrency: 5
:logfile: ./log/shoryuken.log
:timeout: 30
:delay: 0.1
:queues:
  - <%= SQS[:search_etl_queue] %>
  - <%= ES_V2_QUEUE_KEY % { cluster: 'cluster1' } %>
  - <%= ES_V2_QUEUE_KEY % { cluster: 'cluster1-archive' } %>
  - <%= SQS[:facebook_realtime_queue] %>
  - <%= SQS[:fb_message_realtime_queue] %>
  - <%= SQS[:count_etl_queue] %>
  - <%= SQS[:analytics_etl_queue] %>
  - <%= SQS[:free_customer_email_queue] %>
  - <%= SQS[:trial_customer_email_queue] %>
  - <%= SQS[:active_customer_email_queue] %>
  - <%= SQS[:default_email_queue] %>
  - <%= SQS[:email_dead_letter_queue] %>
  - <%= SQS[:scheduled_ticket_export_complete] %>
  - <%= SQS[:scheduled_export_payload_enricher_queue] %>
  - <%= SQS[:channel_framework_services] %>
  - <%= SQS[:fd_scheduler_reminder_todo_queue] %>
  - <%= SQS[:custom_mailbox_status] %>
  - <%= SQS[:bot_feedback_queue] %>
  - <%= SQS[:fd_scheduler_export_cleanup_queue] %>
  - <%= SQS[:spam_trash_delete_free_acc_queue] %>
  - <%= SQS[:spam_trash_delete_paid_acc_queue] %>
  - <%= SQS[:fd_scheduler_downgrade_policy_reminder_queue] %>
  - <%= SQS[:search_etlqueue_maintenance] %>
  - <%= SQS[:count_etl_queue_maintenance] %>
  - <%= SQS[:analytics_etl_queue_maintenance] %>
  - <%= SQS[:suspended_account_cleanup_queue] %>
  - <%= SQS[:email_rate_limiting_queue] %>
  - <%= SQS[:freddy_consumed_session_reminder_queue] %>
  - <%= SQS[:switch_to_annual_notification_queue] %>

