defaults: &defaults
  host: localhost
  port: 6379
  namespace: sidekiqbj
  keepalive: 10
  scheduled_poll_interval: 1

development:
  <<: *defaults

staging:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults