defaults: &defaults
  host: localhost
  port: 6379
  password: ''
  namespace: sidekiqbj
  keepalive: 10

development:
  <<: *defaults

staging:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults