development: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 1
  retry_base_sleep_seconds: 1
production: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 1
  retry_base_sleep_seconds: 1
staging: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 1
  retry_base_sleep_seconds: 1
test:
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update  
  max_tries: 1
  retry_base_sleep_seconds: 1