development: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 4
production: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 4
staging: 
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update
  max_tries: 4
test:
  auth_key: Token ebb87a7e-8e19-4c7d-ad93-89be7ab92e96
  api_endpoint: http://ncstaging.freshworksapi.com
  init_url: /init
  query_url: /query
  feedback_url: /update  
  max_tries: 4
