development:
  social_notification_topic: social_notification_dev
  reports_notification_topic: reports_notification_dev
  dev_ops_notification_topic: dev_ops_notification_dev
  mailbox_notification_topic: mailbox_notification_dev
  activities_notification_topic: activities_notification_dev
  freshdesk_team_notification_topic: freshdesk_team_notification_dev
  associated_tickets_fallback_topic: associated_tickets_fallback_dev
  freshid_notification_topic: freshid_notification_dev
  field_service_management: field_service_management
  fluffy_notification_topic: fluffy_notification_dev
staging:
  social_notification_topic: social_notification_staging
  reports_notification_topic: reports_notification_staging
  dev_ops_notification_topic: dev_ops_notification_staging
  mailbox_notification_topic: mailbox_notification_staging
  activities_notification_topic: activities_notification_staging
  freshdesk_team_notification_topic: freshdesk_team_notification_staging
  associated_tickets_fallback_topic: associated_tickets_fallback_staging
  freshid_notification_topic: freshid_notification_staging
  field_service_management: field_service_management
  fluffy_notification_topic: fluffy_notification_staging
production:
  social_notification_topic: social_notification_production
  reports_notification_topic: reports_notification_production
  dev_ops_notification_topic: dev_ops_notification_production
  mailbox_notification_topic: mailbox_notification_production
  activities_notification_topic: activities_notification_production
  freshdesk_team_notification_topic: freshdesk_team_notification_production
  associated_tickets_fallback_topic: associated_tickets_fallback_production
  freshid_notification_topic: freshid_notification_production
  field_service_management: field_service_management
  fluffy_notification_topic: fluffy_notification_production
test:
  social_notification_topic: social_notification_test
  reports_notification_topic: reports_notification_test
  dev_ops_notification_topic: dev_ops_notification_test
  mailbox_notification_topic: mailbox_notification_test
  activities_notification_topic: activities_notification_test
  freshdesk_team_notification_topic: freshdesk_team_notification_test
  associated_tickets_fallback_topic: associated_tickets_fallback_test
  freshid_notification_topic: freshid_notification_test
  field_service_management: field_service_management
  fluffy_notification_topic: fluffy_notification_test
