defaults: &defaults
  ciphers:
  - key: 1234567890ABCDEF
    iv: 1234567890ABCDEF
    cipher_name: aes-128-cbc
    version: 1

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults