common: &common
  primary_storage: riak
  secondary_storage: mysql
  backup_storage: s3

development:
  primary_storage: mysql
  secondary_storage: none
  backup_storage: none

staging:
  <<: *common

production:
  <<: *common

test:
  primary_storage: mysql
  secondary_storage: none
  backup_storage: none
