defaults: &defaults
  port: 9090
  activities:
    host: 127.0.0.1
  activities_export:
    host: 127.0.0.1

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults