va_handlers:
    rule:
        default: Va::Handlers::Text
        email: Va::Handlers::Email
        text: Va::Handlers::Text
        text_array: Va::Handlers::TextArray
        numeric: Va::Handlers::Numeric
        decimal: Va::Handlers::Decimal
        date_time: Va::Handlers::DateTime
        date: Va::Handlers::Date
        dropdown:  Va::Handlers::Text
        checkbox: Va::Handlers::Boolean
        object_id: Va::Handlers::ObjectId
        object_id_array: Va::Handlers::ObjectIdArray
        nested_field: Va::Handlers::NestedField
        allow_all: Va::Handlers::AllowAll
        date_time_status: Va::Handlers::DateTimeStatus
    event:
        default: Va::EventHandlers::Update
        fallback: Va::EventHandlers::Fallback
        update: Va::EventHandlers::Update # [:from, :to] comparison handler
        value: Va::EventHandlers::Value # :value comparison handler
        change: Va::EventHandlers::Change # doesn't matter what the change is..
        nested_field: Va::EventHandlers::NestedField # for nested_fields
        agent: Va::EventHandlers::Agent # for agent updated event