fields:
    rule:
        default: default
        company_ids: object_id_array
        time_zone: text
        twitter_id: numeric
        created_at: date

        custom_checkbox: checkbox
        custom_number: numeric
        custom_dropdown: dropdown 
        custom_date: date
        missing_field: missing_field

        any: allow_all
        from_email: email
        to_email: email
        subject: text
        description: text
        last_interaction: text
        subject_or_description: text_array
        priority: numeric
        tag_ids: object_id_array
        ticket_type: text
        status: numeric
        source: numeric
        product_id: object_id
        contact: text
        company: text
        responder_id: object_id
        group_id: object_id
        internal_agent_id: object_id
        internal_group_id: object_id
        company_id: object_id
        ticlet_cc: email
        domains: text_array
        renewal_date: date
        segments: object_id_array

        created_during: date_time
        updated_at: date_time
        opened_at: date_time
        pending_since: date_time
        resolved_at: date_time
        closed_at: date_time
        first_assigned_at: date_time
        assigned_at: date_time
        requester_responded_at: date_time
        agent_responded_at: date_time
        first_response_time: date_time
        frDueBy: date_time
        due_by: date_time

        inbound_count: numeric
        outbound_count: numeric
        st_survey_rating: numeric
        customer_feedback: numeric
        folder_id: numeric
        thumbs_up: numeric
        forum_id: numeric
        user_votes: numeric

        note_type: text
        reply_sent: text
        ticket_action: text
        user_action: text
        note_action: text
        time_sheet_action: text

        custom_text: text
        custom_paragraph: text
        custom_decimal: decimal
        nested_field: nested_field
        custom_phone_number: text
        custom_url: text

        freddy_suggestion: freddy_type

    event:
        default: default
        priority: update
        ticket_type: update
        status: update
        responder_id: agent
        group_id: update
        note_type: value
        reply_sent: change
        ticket_action: value
        user_action: value
        company_action: value
        note_action: value
        time_sheet_action: value
        customer_feedback: value
        due_by: change
        mail_del_failed_requester: change
        mail_del_failed_others: change

        custom_checkbox: value
        custom_dropdown: update
        nested_field: nested_field
