type: object
properties:
  automations:
    type: array
    items:
      type: object
      properties:
        automations:
          type: array
          items:
            type: object
            allOf:
              - $ref: '#/definitions/automation_rule'
              - $ref: '#/definitions/automation_rule_common'
              - $ref: '#/definitions/extension_generic'
        meta:
          type: object
          properties:
            count:
              type: integer