defaults: &defaults
  domain: "https://j4zrh65je7.execute-api.us-east-1.amazonaws.com/prod/data"

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
