#!/usr/bin/env ruby
require 'rubygems'
require 'lockfile'

Lockfile('lock', :retries => 0) do
  require File.dirname(__FILE__) + '/../config/boot'
  require File.dirname(__FILE__) + '/../config/environment'
  
  puts "The subscription script file is running "
   
  Subscription.find_expiring_trials.each do |sub|
    puts "Account admin email is #{sub.account.account_admin.email}"
    if admin = sub.account.account_admin
      SubscriptionNotifier.deliver_trial_expiring(admin, sub, "#{sub.trial_days} days")
    end
  end
  
  Subscription.find_expiring_trials(48.hours.from_now).each do |sub|
    puts "Two day admin email is #{sub.account.account_admin.email}"
    if admin = sub.account.account_admin
      SubscriptionNotifier.deliver_trial_expiring(admin, sub, "48 hours")
    end
  end
  
  Subscription.find_expiring_trials(24.hours.from_now).each do |sub|
    puts "One day admin email is #{sub.account.account_admin.email}"
    if admin = sub.account.account_admin
      SubscriptionNotifier.deliver_trial_expiring(admin, sub, "24 hours")
    end
  end
  
  # Trial subscriptions for which we have payment info.
  # This will always turn up empty unless we are collecting 
  # payment info when creating an account.
  Subscription.find_due_trials.each do |sub|
    if !sub.charge
      SubscriptionNotifier.deliver_charge_failure(sub)
    end
  end

  Subscription.find_due.each do |sub|
    if !sub.charge
      SubscriptionNotifier.deliver_charge_failure(sub)
    end
  end

  # Subscriptions overdue for payment (2nd try)
  Subscription.find_due(5.days.ago).each do |sub|
    if !sub.charge
      SubscriptionNotifier.deliver_charge_failure(sub)
    end
  end

end
