#!/usr/bin/env ruby
require 'rubygems'
require 'lockfile'

Lockfile('lock', :retries => 0) do
  require File.dirname(__FILE__) + '/../config/boot'
  require File.dirname(__FILE__) + '/../config/environment'
  
  
  unless RAILS_ENV == "staging"
  
    puts "The subscription script file is running "
  
  end

end
