# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Help Widget Public API documentation
  version: "1.0.0"
# the domain of the service
# array of all schemes that your API supports
# will be prefixed to all paths
basePath: /api/widget
produces:
  - application/json
paths:
  $ref: help_widget/paths/index.yaml
definitions:
  $ref: help_widget/definitions/index.yaml
