/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Freshdesk\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-tag' : '&#x21;',
			'icon-cloud' : '&#x22;',
			'icon-bookmark' : '&#x23;',
			'icon-pencil' : '&#x24;',
			'icon-book' : '&#x25;',
			'icon-list' : '&#x26;',
			'icon-home' : '&#x27;',
			'icon-arrow' : '&#x28;',
			'icon-arrow-2' : '&#x29;',
			'icon-arrow-3' : '&#x2a;',
			'icon-arrow-4' : '&#x2b;',
			'icon-download' : '&#x2c;',
			'icon-upload' : '&#x2d;',
			'icon-cloud-2' : '&#x2e;',
			'icon-document' : '&#x2f;',
			'icon-info' : '&#x30;',
			'icon-info-circle' : '&#x31;',
			'icon-warning' : '&#x32;',
			'icon-google-circles' : '&#x33;',
			'icon-eye' : '&#x34;',
			'icon-share' : '&#x35;',
			'icon-comment' : '&#x36;',
			'icon-chat' : '&#x37;',
			'icon-phone' : '&#x38;',
			'icon-mobile' : '&#x39;',
			'icon-email' : '&#x3a;',
			'icon-attachment' : '&#x3b;',
			'icon-write' : '&#x3c;',
			'icon-reply' : '&#x3d;',
			'icon-forward' : '&#x3e;',
			'icon-reply-to-all' : '&#x3f;',
			'icon-card' : '&#x40;',
			'icon-bolt' : '&#x41;',
			'icon-equalizer' : '&#x42;',
			'icon-headphones' : '&#x43;',
			'icon-iphone' : '&#x44;',
			'icon-unlock-fill' : '&#x45;',
			'icon-unlock-stroke' : '&#x46;',
			'icon-lock-fill' : '&#x47;',
			'icon-lock-stroke' : '&#x48;',
			'icon-checkmark' : '&#x49;',
			'icon-x' : '&#x4a;',
			'icon-facebook' : '&#x4b;',
			'icon-facebook-2' : '&#x4c;',
			'icon-twitter' : '&#x4d;',
			'icon-twitter-2' : '&#x4e;',
			'icon-twitter-3' : '&#x4f;',
			'icon-locked' : '&#x50;',
			'icon-unlocked' : '&#x51;',
			'icon-mail' : '&#x52;',
			'icon-arrow-left' : '&#x53;',
			'icon-arrow-right' : '&#x54;',
			'icon-arrow-down' : '&#x55;',
			'icon-arrow-up' : '&#x56;',
			'icon-unlocked-2' : '&#x57;',
			'icon-locked-2' : '&#x58;',
			'icon-bolt-2' : '&#x59;',
			'icon-list-2' : '&#x5a;',
			'icon-trashcan' : '&#x5b;',
			'icon-minus' : '&#x5c;',
			'icon-plus' : '&#x5d;',
			'icon-close' : '&#x5e;',
			'icon-checkmark-2' : '&#x5f;',
			'icon-switch' : '&#x60;',
			'icon-comment-2' : '&#x61;',
			'icon-phone-2' : '&#x62;',
			'icon-comments' : '&#x63;',
			'icon-comments-2' : '&#x64;',
			'icon-undo' : '&#x65;',
			'icon-redo' : '&#x66;',
			'icon-user' : '&#x67;',
			'icon-search' : '&#x68;',
			'icon-remove' : '&#x69;',
			'icon-remove-2' : '&#x6a;',
			'icon-remove-3' : '&#x6b;',
			'icon-link' : '&#x6c;',
			'icon-flag' : '&#x6d;',
			'icon-google-plus' : '&#x6e;',
			'icon-google-plus-2' : '&#x6f;',
			'icon-gplus' : '&#x70;',
			'icon-facebook-3' : '&#x71;',
			'icon-facebook-4' : '&#x72;',
			'icon-lines' : '&#x73;',
			'icon-plus-alt' : '&#x74;',
			'icon-minus-alt' : '&#x75;',
			'icon-pin' : '&#x76;',
			'icon-trash-fill' : '&#x77;',
			'icon-trash-stroke' : '&#x78;',
			'icon-key-stroke' : '&#x79;',
			'icon-key-fill' : '&#x7a;',
			'icon-contact' : '&#x7b;',
			'icon-users' : '&#x7c;',
			'icon-quote' : '&#x7d;',
			'icon-flash' : '&#x7e;',
			'icon-list-3' : '&#xe000;',
			'icon-paperclip' : '&#xe001;',
			'icon-phone-3' : '&#xe002;',
			'icon-warning-2' : '&#xe003;',
			'icon-key' : '&#xe004;',
			'icon-globe' : '&#xe005;',
			'icon-dots-three' : '&#xe006;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^s'"]+/);
		if (c) {
			addIcon(el, icons[c[0]]);
		}
	}
};