class ChangeIdsToLongForForeignKeys < ActiveRecord::Migration
  def self.up
    columns_to_change.each do |c|
      change_column c[0], c[1], :integer, :limit => 8
    end
    
    change_column :solution_articles, :description, :text, :limit => 65540
  end
  
  def self.columns_to_change
    [
      [ :accounts,                  :ticket_display_id ],
      [ :agent_groups,              :user_id ],
      [ :agent_groups,              :group_id ],
      [ :agents,                    :user_id ],
      [ :business_calendars,        :account_id ],
      [ :customers,                 :account_id ],
      [ :customers,                 :sla_policy_id ],
      [ :email_configs,             :account_id ],
      [ :email_configs,             :group_id ],
      [ :email_notifications,       :account_id ],
      [ :flexifield_def_entries,    :flexifield_def_id ],
      [ :flexifield_defs,           :account_id ],
      [ :flexifield_picklist_vals,  :flexifield_def_entry_id ],
      [ :flexifields,               :flexifield_def_id ],
      [ :flexifields,               :flexifield_set_id ],
      [ :forum_categories,          :account_id ],
      [ :forums,                    :account_id ],
      [ :forums,                    :forum_category_id ],
      [ :groups,                    :account_id ],
      [ :groups,                    :escalate_to ],
      [ :helpdesk_activities,       :account_id ],
      [ :helpdesk_activities,       :notable_id ],
      [ :helpdesk_activities,       :user_id ],
      [ :helpdesk_attachments,      :attachable_id ],
      [ :helpdesk_attachments,      :account_id ],
      [ :helpdesk_form_customizers, :account_id ],
      [ :helpdesk_notes,            :user_id ],
      [ :helpdesk_notes,            :notable_id ],
      [ :helpdesk_notes,            :account_id ],
      [ :helpdesk_reminders,        :user_id ],
      [ :helpdesk_reminders,        :ticket_id ],
      [ :helpdesk_sla_details,      :priority ],
      [ :helpdesk_sla_details,      :escalateto ],
      [ :helpdesk_sla_details,      :sla_policy_id ],
      [ :helpdesk_sla_policies,     :account_id ],
      [ :helpdesk_subscriptions,    :user_id ],
      [ :helpdesk_subscriptions,    :ticket_id ],
      [ :helpdesk_tag_uses,         :tag_id ],
      [ :helpdesk_tag_uses,         :taggable_id ],
      [ :helpdesk_tags,             :account_id ],
      [ :helpdesk_tickets,          :requester_id ],
      [ :helpdesk_tickets,          :responder_id ],
      [ :helpdesk_tickets,          :status ],
      [ :helpdesk_tickets,          :account_id ],
      [ :helpdesk_tickets,          :display_id ],
      [ :helpdesk_tickets,          :owner_id ],
      [ :helpdesk_tickets,          :group_id ],
      [ :helpdesk_tickets,          :priority ],
      [ :helpdesk_tickets,          :ticket_type ],
      [ :helpdesk_tickets,          :email_config_id ],
      [ :moderatorships,            :forum_id ],
      [ :moderatorships,            :user_id ],
      [ :monitorships,              :topic_id ],
      [ :monitorships,              :user_id ],
      [ :password_resets,           :user_id ],
      [ :posts,                     :user_id ],
      [ :posts,                     :topic_id ],
      [ :posts,                     :forum_id ],
      [ :posts,                     :account_id ],
      [ :solution_articles,         :user_id ],
      [ :solution_articles,         :folder_id ],
      [ :solution_articles,         :account_id ],
      [ :solution_categories,       :account_id ],
      [ :solution_folders,          :category_id ],
      [ :subscription_payments,     :account_id ],
      [ :subscription_payments,     :subscription_id ],
      [ :subscription_payments,     :subscription_affiliate_id ],
      [ :subscriptions,             :subscription_plan_id ],
      [ :subscriptions,             :account_id ],
      [ :subscriptions,             :subscription_discount_id ],
      [ :subscriptions,             :subscription_affiliate_id ],
      [ :ticket_topics,             :ticket_id ],
      [ :ticket_topics,             :topic_id ],
      [ :topics,                    :forum_id ],
      [ :topics,                    :user_id ],
      [ :topics,                    :replied_by ],
      [ :topics,                    :last_post_id ],
      [ :topics,                    :account_id ],
      [ :users,                     :account_id ],
      [ :users,                     :customer_id ],
      [ :va_rules,                  :account_id ],
      [ :votes,                     :voteable_id ],
      [ :votes,                     :user_id ]
    ]
  end

  def self.down
  end
end
