class CreateContactFlexifields < ActiveRecord::Migration
  shard :all
  def self.up
    execute(%(
      CREATE TABLE `contact_flexifields` (
        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
        `account_id` bigint(20) DEFAULT NULL,
        `flexifield_def_id` bigint(20) DEFAULT NULL,
        `user_id` bigint(20) DEFAULT NULL,
        `created_at` datetime DEFAULT NULL,
        `updated_at` datetime DEFAULT NULL,
        `ffs_01` varchar(255) DEFAULT NULL,
        `ffs_02` varchar(255) DEFAULT NULL,
        `ffs_03` varchar(255) DEFAULT NULL,
        `ffs_04` varchar(255) DEFAULT NULL,
        `ffs_05` varchar(255) DEFAULT NULL,
        `ffs_06` varchar(255) DEFAULT NULL,
        `ffs_07` varchar(255) DEFAULT NULL,
        `ffs_08` varchar(255) DEFAULT NULL,
        `ffs_09` varchar(255) DEFAULT NULL,
        `ffs_10` varchar(255) DEFAULT NULL,
        `ffs_11` varchar(255) DEFAULT NULL,
        `ffs_12` varchar(255) DEFAULT NULL,
        `ffs_13` varchar(255) DEFAULT NULL,
        `ffs_14` varchar(255) DEFAULT NULL,
        `ffs_15` varchar(255) DEFAULT NULL,
        `ffs_16` varchar(255) DEFAULT NULL,
        `ffs_17` varchar(255) DEFAULT NULL,
        `ffs_18` varchar(255) DEFAULT NULL,
        `ffs_19` varchar(255) DEFAULT NULL,
        `ffs_20` varchar(255) DEFAULT NULL,
        `ffs_21` varchar(255) DEFAULT NULL,
        `ffs_22` varchar(255) DEFAULT NULL,
        `ffs_23` varchar(255) DEFAULT NULL,
        `ffs_24` varchar(255) DEFAULT NULL,
        `ffs_25` varchar(255) DEFAULT NULL,
        `ffs_26` varchar(255) DEFAULT NULL,
        `ffs_27` varchar(255) DEFAULT NULL,
        `ffs_28` varchar(255) DEFAULT NULL,
        `ffs_29` varchar(255) DEFAULT NULL,
        `ffs_30` varchar(255) DEFAULT NULL,
        `ffs_31` varchar(255) DEFAULT NULL,
        `ffs_32` varchar(255) DEFAULT NULL,
        `ffs_33` varchar(255) DEFAULT NULL,
        `ffs_34` varchar(255) DEFAULT NULL,
        `ffs_35` varchar(255) DEFAULT NULL,
        `ffs_36` varchar(255) DEFAULT NULL,
        `ffs_37` varchar(255) DEFAULT NULL,
        `ffs_38` varchar(255) DEFAULT NULL,
        `ffs_39` varchar(255) DEFAULT NULL,
        `ffs_40` varchar(255) DEFAULT NULL,
        `ffs_41` varchar(255) DEFAULT NULL,
        `ffs_42` varchar(255) DEFAULT NULL,
        `ffs_43` varchar(255) DEFAULT NULL,
        `ffs_44` varchar(255) DEFAULT NULL,
        `ffs_45` varchar(255) DEFAULT NULL,
        `ffs_46` varchar(255) DEFAULT NULL,
        `ffs_47` varchar(255) DEFAULT NULL,
        `ffs_48` varchar(255) DEFAULT NULL,
        `ffs_49` varchar(255) DEFAULT NULL,
        `ffs_50` varchar(255) DEFAULT NULL,
        `ffs_51` varchar(255) DEFAULT NULL,
        `ffs_52` varchar(255) DEFAULT NULL,
        `ffs_53` varchar(255) DEFAULT NULL,
        `ffs_54` varchar(255) DEFAULT NULL,
        `ffs_55` varchar(255) DEFAULT NULL,
        `ffs_56` varchar(255) DEFAULT NULL,
        `ffs_57` varchar(255) DEFAULT NULL,
        `ffs_58` varchar(255) DEFAULT NULL,
        `ffs_59` varchar(255) DEFAULT NULL,
        `ffs_60` varchar(255) DEFAULT NULL,
        `ffs_61` varchar(255) DEFAULT NULL,
        `ffs_62` varchar(255) DEFAULT NULL,
        `ffs_63` varchar(255) DEFAULT NULL,
        `ffs_64` varchar(255) DEFAULT NULL,
        `ffs_65` varchar(255) DEFAULT NULL,
        `ffs_66` varchar(255) DEFAULT NULL,
        `ffs_67` varchar(255) DEFAULT NULL,
        `ffs_68` varchar(255) DEFAULT NULL,
        `ffs_69` varchar(255) DEFAULT NULL,
        `ffs_70` varchar(255) DEFAULT NULL,
        `ffs_71` varchar(255) DEFAULT NULL,
        `ffs_72` varchar(255) DEFAULT NULL,
        `ffs_73` varchar(255) DEFAULT NULL,
        `ffs_74` varchar(255) DEFAULT NULL,
        `ffs_75` varchar(255) DEFAULT NULL,
        `ffs_76` varchar(255) DEFAULT NULL,
        `ffs_77` varchar(255) DEFAULT NULL,
        `ffs_78` varchar(255) DEFAULT NULL,
        `ffs_79` varchar(255) DEFAULT NULL,
        `ffs_80` varchar(255) DEFAULT NULL,
        `ff_text01` text,
        `ff_text02` text,
        `ff_text03` text,
        `ff_text04` text,
        `ff_text05` text,
        `ff_text06` text,
        `ff_text07` text,
        `ff_text08` text,
        `ff_text09` text,
        `ff_text10` text,
        `ff_int01` int(11) DEFAULT NULL,
        `ff_int02` int(11) DEFAULT NULL,
        `ff_int03` int(11) DEFAULT NULL,
        `ff_int04` int(11) DEFAULT NULL,
        `ff_int05` int(11) DEFAULT NULL,
        `ff_int06` int(11) DEFAULT NULL,
        `ff_int07` int(11) DEFAULT NULL,
        `ff_int08` int(11) DEFAULT NULL,
        `ff_int09` int(11) DEFAULT NULL,
        `ff_int10` int(11) DEFAULT NULL,
        `ff_int11` int(11) DEFAULT NULL,
        `ff_int12` int(11) DEFAULT NULL,
        `ff_int13` int(11) DEFAULT NULL,
        `ff_int14` int(11) DEFAULT NULL,
        `ff_int15` int(11) DEFAULT NULL,
        `ff_int16` int(11) DEFAULT NULL,
        `ff_int17` int(11) DEFAULT NULL,
        `ff_int18` int(11) DEFAULT NULL,
        `ff_int19` int(11) DEFAULT NULL,
        `ff_int20` int(11) DEFAULT NULL,
        `ff_date01` datetime DEFAULT NULL,
        `ff_date02` datetime DEFAULT NULL,
        `ff_date03` datetime DEFAULT NULL,
        `ff_date04` datetime DEFAULT NULL,
        `ff_date05` datetime DEFAULT NULL,
        `ff_date06` datetime DEFAULT NULL,
        `ff_date07` datetime DEFAULT NULL,
        `ff_date08` datetime DEFAULT NULL,
        `ff_date09` datetime DEFAULT NULL,
        `ff_date10` datetime DEFAULT NULL,
        `ff_boolean01` tinyint(1) DEFAULT NULL,
        `ff_boolean02` tinyint(1) DEFAULT NULL,
        `ff_boolean03` tinyint(1) DEFAULT NULL,
        `ff_boolean04` tinyint(1) DEFAULT NULL,
        `ff_boolean05` tinyint(1) DEFAULT NULL,
        `ff_boolean06` tinyint(1) DEFAULT NULL,
        `ff_boolean07` tinyint(1) DEFAULT NULL,
        `ff_boolean08` tinyint(1) DEFAULT NULL,
        `ff_boolean09` tinyint(1) DEFAULT NULL,
        `ff_boolean10` tinyint(1) DEFAULT NULL,
        `ff_decimal01` int(11) DEFAULT NULL,
        `ff_decimal02` int(11) DEFAULT NULL,
        `ff_decimal03` int(11) DEFAULT NULL,
        `ff_decimal04` int(11) DEFAULT NULL,
        `ff_decimal05` int(11) DEFAULT NULL,
        `ff_decimal06` int(11) DEFAULT NULL,
        `ff_decimal07` int(11) DEFAULT NULL,
        `ff_decimal08` int(11) DEFAULT NULL,
        `ff_decimal09` int(11) DEFAULT NULL,
        `ff_decimal10` int(11) DEFAULT NULL,
        `long_uc01` bigint(20) DEFAULT NULL,
        `long_uc02` bigint(20) DEFAULT NULL,
        `long_uc03` bigint(20) DEFAULT NULL,
        `long_uc04` bigint(20) DEFAULT NULL,
        `long_uc05` bigint(20) DEFAULT NULL,
        `int_uc01` int(11) DEFAULT NULL,
        `int_uc02` int(11) DEFAULT NULL,
        `int_uc03` int(11) DEFAULT NULL,
        `int_uc04` int(11) DEFAULT NULL,
        `int_uc05` int(11) DEFAULT NULL,
        `string_uc07` varchar(255) DEFAULT NULL,
        `string_uc08` varchar(255) DEFAULT NULL,
        `string_uc09` varchar(255) DEFAULT NULL,
        `string_uc10` varchar(255) DEFAULT NULL,
        `string_uc11` varchar(255) DEFAULT NULL,
        `string_uc12` varchar(255) DEFAULT NULL,
        `datetime_uc01` datetime DEFAULT NULL,
        `datetime_uc02` datetime DEFAULT NULL,
        `boolean_uc01` tinyint(1) DEFAULT '0',
        `boolean_uc02` tinyint(1) DEFAULT '0',
        `boolean_uc03` tinyint(1) DEFAULT '0',
        `boolean_uc04` tinyint(1) DEFAULT '0',
        `boolean_uc05` tinyint(1) DEFAULT '0',
        `text_uc02` text,
        PRIMARY KEY (`id`),
        UNIQUE KEY `index_contact_flexifields_on_account_id_and_user_id` (`account_id`,`user_id`),
        KEY `index_contact_flexifields_on_account_id_and_flexifield_def_id` (`account_id`,`flexifield_def_id`),
        KEY `index_contact_flexifields_on_account_id_and_long_uc01` (`account_id`,`long_uc01`),
        KEY `index_contact_flexifields_on_account_id_and_long_uc02` (`account_id`,`long_uc02`),
        KEY `index_contact_flexifields_on_account_id_and_int_uc01` (`account_id`,`int_uc01`),
        KEY `index_contact_flexifields_on_account_id_and_int_uc02` (`account_id`,`int_uc02`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    ))
  end
end
