class AddMoreFieldsToFlexifields < ActiveRecord::Migration
  shard :all

  def self.up
    execute <<-SQL
      ALTER TABLE `flexifields` 
        CHANGE `ff_int01` `ff_int01` bigint(20) DEFAULT NULL,
        CHANGE `ff_int02` `ff_int02` bigint(20) DEFAULT NULL,
        CHANGE `ff_int03` `ff_int03` bigint(20) DEFAULT NULL,
        CHANGE `ff_int04` `ff_int04` bigint(20) DEFAULT NULL,
        CHANGE `ff_int05` `ff_int05` bigint(20) DEFAULT NULL,
        CHANGE `ff_int06` `ff_int06` bigint(20) DEFAULT NULL,
        CHANGE `ff_int07` `ff_int07` bigint(20) DEFAULT NULL,
        CHANGE `ff_int08` `ff_int08` bigint(20) DEFAULT NULL,
        CHANGE `ff_int09` `ff_int09` bigint(20) DEFAULT NULL,
        CHANGE `ff_int10` `ff_int10` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int11` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int12` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int13` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int14` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int15` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int16` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int17` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int18` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int19` bigint(20) DEFAULT NULL,
        ADD COLUMN `ff_int20` bigint(20) DEFAULT NULL,
        ADD COLUMN `ffs_31` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_32` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_33` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_34` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_35` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_36` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_37` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_38` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_39` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_40` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_41` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_42` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_43` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_44` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_45` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_46` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_47` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_48` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_49` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_50` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_51` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_52` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_53` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_54` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_55` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_56` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_57` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_58` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_59` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_60` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_61` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_62` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_63` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_64` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_65` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_66` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_67` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_68` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_69` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_70` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_71` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_72` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_73` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_74` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_75` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_76` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_77` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_78` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_79` varchar(255) DEFAULT NULL,
        ADD COLUMN `ffs_80` varchar(255) DEFAULT NULL,
        ADD COLUMN `ff_decimal01` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal02` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal03` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal04` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal05` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal06` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal07` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal08` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal09` decimal(10,2) DEFAULT NULL,
        ADD COLUMN `ff_decimal10` decimal(10,2) DEFAULT NULL;
    SQL
  end

  def self.down
    execute <<-SQL
      ALTER TABLE `flexifields` 
        CHANGE `ff_int01` `ff_int01` int(11) DEFAULT NULL,
        CHANGE `ff_int02` `ff_int02` int(11) DEFAULT NULL,
        CHANGE `ff_int03` `ff_int03` int(11) DEFAULT NULL,
        CHANGE `ff_int04` `ff_int04` int(11) DEFAULT NULL,
        CHANGE `ff_int05` `ff_int05` int(11) DEFAULT NULL,
        CHANGE `ff_int06` `ff_int06` int(11) DEFAULT NULL,
        CHANGE `ff_int07` `ff_int07` int(11) DEFAULT NULL,
        CHANGE `ff_int08` `ff_int08` int(11) DEFAULT NULL,
        CHANGE `ff_int09` `ff_int09` int(11) DEFAULT NULL,
        CHANGE `ff_int10` `ff_int10` int(11) DEFAULT NULL,
        DROP COLUMN `ff_int11`,
        DROP COLUMN `ff_int12`,
        DROP COLUMN `ff_int13`,
        DROP COLUMN `ff_int14`,
        DROP COLUMN `ff_int15`,
        DROP COLUMN `ff_int16`,
        DROP COLUMN `ff_int17`,
        DROP COLUMN `ff_int18`,
        DROP COLUMN `ff_int19`,
        DROP COLUMN `ff_int20`,
        DROP COLUMN `ffs_31`,
        DROP COLUMN `ffs_32`,
        DROP COLUMN `ffs_33`,
        DROP COLUMN `ffs_34`,
        DROP COLUMN `ffs_35`,
        DROP COLUMN `ffs_36`,
        DROP COLUMN `ffs_37`,
        DROP COLUMN `ffs_38`,
        DROP COLUMN `ffs_39`,
        DROP COLUMN `ffs_40`,
        DROP COLUMN `ffs_41`,
        DROP COLUMN `ffs_42`,
        DROP COLUMN `ffs_43`,
        DROP COLUMN `ffs_44`,
        DROP COLUMN `ffs_45`,
        DROP COLUMN `ffs_46`,
        DROP COLUMN `ffs_47`,
        DROP COLUMN `ffs_48`,
        DROP COLUMN `ffs_49`,
        DROP COLUMN `ffs_50`,
        DROP COLUMN `ffs_51`,
        DROP COLUMN `ffs_52`,
        DROP COLUMN `ffs_53`,
        DROP COLUMN `ffs_54`,
        DROP COLUMN `ffs_55`,
        DROP COLUMN `ffs_56`,
        DROP COLUMN `ffs_57`,
        DROP COLUMN `ffs_58`,
        DROP COLUMN `ffs_59`,
        DROP COLUMN `ffs_60`,
        DROP COLUMN `ffs_61`,
        DROP COLUMN `ffs_62`,
        DROP COLUMN `ffs_63`,
        DROP COLUMN `ffs_64`,
        DROP COLUMN `ffs_65`,
        DROP COLUMN `ffs_66`,
        DROP COLUMN `ffs_67`,
        DROP COLUMN `ffs_68`,
        DROP COLUMN `ffs_69`,
        DROP COLUMN `ffs_70`,
        DROP COLUMN `ffs_71`,
        DROP COLUMN `ffs_72`,
        DROP COLUMN `ffs_73`,
        DROP COLUMN `ffs_74`,
        DROP COLUMN `ffs_75`,
        DROP COLUMN `ffs_76`,
        DROP COLUMN `ffs_77`,
        DROP COLUMN `ffs_78`,
        DROP COLUMN `ffs_79`,
        DROP COLUMN `ffs_80`,
        DROP COLUMN `ff_decimal01`,
        DROP COLUMN `ff_decimal02`,
        DROP COLUMN `ff_decimal03`,
        DROP COLUMN `ff_decimal04`,
        DROP COLUMN `ff_decimal05`,
        DROP COLUMN `ff_decimal06`,
        DROP COLUMN `ff_decimal07`,
        DROP COLUMN `ff_decimal08`,
        DROP COLUMN `ff_decimal09`,
        DROP COLUMN `ff_decimal10`;
    SQL
  end
end
