class AddAllAddonsForLegacyPlansMigration < ActiveRecord::Migration
  shard :none
  def self.up
    addon_types = Subscription::Addon::ADDON_TYPES
    execute <<-SQL
      INSERT INTO subscription_addons
        (name, amount, renewal_period, addon_type, created_at, updated_at) VALUES
        ("SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector CustomerJourney Forum Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector CustomerJourney Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector DynamicSections Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector FbAdPosts Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation ThankyouDetector Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaAutomation Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("ThankyouDetector SmartFilter Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Sandbox Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Whitelisting Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("UnlimitedMultiProduct AuditLog SmartFilter Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("UnlimitedMultiProduct ThankyouDetector SmartFilter Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation ArticleVersioning ThankyouDetector Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation ArticleVersioning DynamicSections Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation ArticleVersioning Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW()),
        ("SlaManagementAutomation SmartFilter ThankyouDetector Migration", 0.0, 1, "#{addon_types[:for_account]}", NOW(), NOW())
    SQL
    execute <<-SQL
      INSERT INTO subscription_plan_addons
        (subscription_plan_id, subscription_addon_id) VALUES
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector CustomerJourney Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Blossom Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaAutomation Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Sandbox Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Sandbox Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Whitelisting Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Whitelisting Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct AuditLog SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "UnlimitedMultiProduct ThankyouDetector SmartFilter Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation ArticleVersioning Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Garden Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector Migration")),
        ((SELECT id FROM subscription_plans WHERE name = "Estate Omni Jan 20"),
          (SELECT id FROM subscription_addons WHERE name = "SlaManagementAutomation SmartFilter ThankyouDetector Migration"))
    SQL
  end

  def self.down
    execute <<-SQL
      DELETE FROM subscription_plan_addons WHERE subscription_addon_id
        IN (SELECT id FROM subscription_addons WHERE name IN ( "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration",
        "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration", "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration",
        "SlaAutomation ThankyouDetector CustomerJourney Forum Migration", "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration",
        "SlaAutomation ThankyouDetector CustomerJourney Migration", "SlaAutomation ThankyouDetector DynamicSections Migration",
        "SlaAutomation ThankyouDetector FbAdPosts Migration", "SlaAutomation ThankyouDetector Migration",
        "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration", "SlaAutomation Migration",
        "ThankyouDetector SmartFilter Migration", "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Sandbox Migration",
        "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Whitelisting Migration", "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Migration",
        "UnlimitedMultiProduct AuditLog SmartFilter Migration", "UnlimitedMultiProduct ThankyouDetector SmartFilter Migration",
        "SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration","SlaManagementAutomation ArticleVersioning ThankyouDetector Migration",
        "SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration", "SlaManagementAutomation ArticleVersioning DynamicSections Migration",
        "SlaManagementAutomation ArticleVersioning Migration", "SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration",
        "SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration", "SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration",
        "SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration", "SlaManagementAutomation SmartFilter ThankyouDetector Migration"
        ))
    SQL
    execute <<-SQL
      DELETE FROM subscription_addons WHERE name IN ( "SlaAutomation ThankyouDetector CustomerJourney DynamicSections Migration",
        "SlaAutomation ThankyouDetector CustomerJourney FbAdPosts Migration", "SlaAutomation ThankyouDetector CustomerJourney Forum FbAdPosts Migration",
        "SlaAutomation ThankyouDetector CustomerJourney Forum Migration", "SlaAutomation ThankyouDetector CustomerJourney Supervisor Migration",
        "SlaAutomation ThankyouDetector CustomerJourney Migration", "SlaAutomation ThankyouDetector DynamicSections Migration",
        "SlaAutomation ThankyouDetector FbAdPosts Migration", "SlaAutomation ThankyouDetector Migration",
        "SlaAutomation Supervisor DynamicSections FbAdPosts Forum Migration", "SlaAutomation Migration",
        "ThankyouDetector SmartFilter Migration", "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Sandbox Migration",
        "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Whitelisting Migration", "UnlimitedMultiProduct AuditLog ThankyouDetector SmartFilter Migration",
        "UnlimitedMultiProduct AuditLog SmartFilter Migration", "UnlimitedMultiProduct ThankyouDetector SmartFilter Migration",
        "SlaManagementAutomation ArticleVersioning ThankyouDetector FbAdPosts Migration","SlaManagementAutomation ArticleVersioning ThankyouDetector Migration",
        "SlaManagementAutomation ArticleVersioning DynamicSections ThankyouDetector Migration", "SlaManagementAutomation ArticleVersioning DynamicSections Migration",
        "SlaManagementAutomation ArticleVersioning Migration", "SlaManagementAutomation SmartFilter ThankyouDetector ChatRouting Migration",
        "SlaManagementAutomation SmartFilter ThankyouDetector CustomSurvey Migration", "SlaManagementAutomation SmartFilter ThankyouDetector DynamicSections Migration",
        "SlaManagementAutomation SmartFilter ThankyouDetector FbAdPosts Migration", "SlaManagementAutomation SmartFilter ThankyouDetector Migration")
    SQL
  end
end
