:customer_interactions: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:agent_interactions: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:agent_reassign_count: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:group_reassign_count: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:reopen_count: 
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:first_response_time: 
  - operator: less_than_eql
    value: 900
    label: < 15 mins
  - operator: range
    value: "900,1800"
    label: 15-30 mins
  - operator: range
    value: "1800,3600"
    label: 30-60 mins
  - operator: range
    value: "3600,7200"
    label: 1-2 hrs
  - operator: range
    value: "7200,14400"
    label: 2-4 hrs
  - operator: range
    value: "14400,28800"
    label: 4-8 hrs
  - operator: range
    value: "28800,43200"
    label: 8-12 hrs
  - operator: range
    value: "43200,86400"
    label: 12-24 hrs
  - operator: range
    value: "86400,172800"
    label: 24-48 hrs
  - operator: greater_than_eql
    value: 172800
    label: 48+ hrs
:response_time: 
  - operator: less_than_eql
    value: 900
    label: < 15 mins
  - operator: range
    value: "900,1800"
    label: 15-30 mins
  - operator: range
    value: "1800,3600"
    label: 30-60 mins
  - operator: range
    value: "3600,7200"
    label: 1-2 hrs
  - operator: range
    value: "7200,14400"
    label: 2-4 hrs
  - operator: range
    value: "14400,28800"
    label: 4-8 hrs
  - operator: range
    value: "28800,43200"
    label: 8-12 hrs
  - operator: range
    value: "43200,86400"
    label: 12-24 hrs
  - operator: range
    value: "86400,172800"
    label: 24-48 hrs
  - operator: greater_than_eql
    value: 172800
    label: 48+ hrs
:resolution_time: 
  - operator: less_than_eql
    value: 18000
    label: < 5 hrs
  - operator: range
    value: "18000,36000"
    label: 5-10 hrs
  - operator: range
    value: "36000,54000"
    label: 10-15 hrs
  - operator: range
    value: "54000,90000"
    label: 15-25 hrs
  - operator: range
    value: "90000,180000"
    label: 25-50 hrs
  - operator: range
    value: "180000,360000"
    label: 50-100 hrs  
  - operator: range
    value: "360000,720000"
    label: 100-200 hrs  
  - operator: range
    value: "720000,1260000"
    label: 200-350 hrs 
  - operator: range
    value: "1260000,2520000"
    label: 350-700 hrs
  - operator: greater_than_eql
    value: 2520000
    label: 700+ hrs
:reply_count: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
:private_note_count: 
  - operator: eql
    value: 0
    label: 0
  - operator: eql
    value: 1
    label: 1
  - operator: eql
    value: 2
    label: 2
  - operator: eql
    value: 3
    label: 3
  - operator: eql
    value: 4
    label: 4
  - operator: greater_than_eql
    value: 5
    label: 5+
