
:insights_threshold_values:
  :forest:
    :group1:
      RECEIVED_TICKETS: 15
      RESOLVED_TICKETS: 5
      UNRESOLVED_TICKETS: 2
      REOPENED_TICKETS: 10
      AVG_FIRST_RESPONSE_TIME: 42
      AVG_RESPONSE_TIME: 4
      AVG_RESOLUTION_TIME: 85
      AVG_FIRST_ASSIGN_TIME: 36
      RESPONSE_SLA: 3
      RESOLUTION_SLA: 3
      GROUP_COMPARE_METRIC: 10
    :group2:
      RECEIVED_TICKETS: 5
      RESOLVED_TICKETS: 18
      UNRESOLVED_TICKETS: 2
      REOPENED_TICKETS: 12
      AVG_FIRST_RESPONSE_TIME: 54
      AVG_RESPONSE_TIME: 85
      AVG_RESOLUTION_TIME: 85
      AVG_FIRST_ASSIGN_TIME: 7
      RESPONSE_SLA: 14
      RESOLUTION_SLA: 2
      GROUP_COMPARE_METRIC: 10
    :group3:
      RECEIVED_TICKETS: 3
      RESOLVED_TICKETS: 43
      UNRESOLVED_TICKETS: 23
      REOPENED_TICKETS: 3
      AVG_FIRST_RESPONSE_TIME: 29
      AVG_RESPONSE_TIME: 25
      AVG_RESOLUTION_TIME: 23
      AVG_FIRST_ASSIGN_TIME: 32
      RESPONSE_SLA: 18
      RESOLUTION_SLA: 37
      GROUP_COMPARE_METRIC: 10
  :estate:
    :group1:
      RECEIVED_TICKETS: 8
      RESOLVED_TICKETS: 21
      UNRESOLVED_TICKETS: 3
      REOPENED_TICKETS: 18
      AVG_FIRST_RESPONSE_TIME: 44
      AVG_RESPONSE_TIME: 64
      AVG_RESOLUTION_TIME: 27
      AVG_FIRST_ASSIGN_TIME: 15
      RESPONSE_SLA: 5
      RESOLUTION_SLA: 1
      GROUP_COMPARE_METRIC: 10
    :group2:
      RECEIVED_TICKETS: 15
      RESOLVED_TICKETS: 9
      UNRESOLVED_TICKETS: 6
      REOPENED_TICKETS: 33
      AVG_FIRST_RESPONSE_TIME: 40
      AVG_RESPONSE_TIME: 85
      AVG_RESOLUTION_TIME: 85
      AVG_FIRST_ASSIGN_TIME: 13
      RESPONSE_SLA: 13
      RESOLUTION_SLA: 3
      GROUP_COMPARE_METRIC: 10
    :group3:
      RECEIVED_TICKETS: 5
      RESOLVED_TICKETS: 26
      UNRESOLVED_TICKETS: 15
      REOPENED_TICKETS: 10
      AVG_FIRST_RESPONSE_TIME: 27
      AVG_RESPONSE_TIME: 36
      AVG_RESOLUTION_TIME: 10
      AVG_FIRST_ASSIGN_TIME: 22
      RESPONSE_SLA: 6
      RESOLUTION_SLA: 1
      GROUP_COMPARE_METRIC: 10
