defaults: &defaults
  host: "reports-servie-628547972.us-east-1.elb.amazonaws.com"
  ticket_reports: "/enterprise_reports/execute/"
  timesheet_reports: "/example/execute"

development:
 <<: *defaults
staging:
  host: "http://10.170.148.112:80"
  ticket_reports: "/enterprise_reports/execute/"
  timesheet_reports: "/example/execute"
test:
 <<: *defaults