defaults: &defaults
  host: "reports-service-1847906171.us-east-1.elb.amazonaws.com"
  ticket_reports: "/enterprise_reports/execute/%{priority}"
  timesheet_reports: "/example/execute"
  web_req_timeout: 60
  bg_req_timeout: 120

development:
 <<: *defaults
staging:
  host: "http://10.170.148.112:80"
  ticket_reports: "/enterprise_reports/execute/"
  timesheet_reports: "/example/execute"
test:
 <<: *defaults