get:
  tags: [search]
  summary: Search Automations
  parameters:
    - name: term
      in: query
      type: string
      description: search term for automations
      required: true
    - name: query
      in: query
      type: string
      description: search filter for automations
  responses:
    200:
      description: Success
      schema:
        type: array
        items:
          $ref: '#/definitions/automation_search'
    400:
      description: Bad Request Error
      schema:
        $ref: '#/definitions/bad_request_error'
    403:
      description: Access denied