module Admin::HolidaysConstants
  GOOGLE_CALENDAR_ID_SUFFIX = '#holiday@group.v.calendar.google.com'.freeze
  HOLIDAYS_WITH_CODES =
  [
    ['Holidays in Andorra', 'en-gb.ad', 'AD'],
    ['Holidays in the United Arab Emirates', 'en-gb.ae', 'AE'],
    ['Holidays in Afghanistan', 'en-gb.af', 'AF'],
    ['Holidays in Albania', 'en-gb.al', 'AL'],
    ['Holidays in Armenia', 'en-gb.am', 'AM'],
    ['Holidays in Angola', 'en-gb.ao', 'AO'],
    ['Holidays in Argentina', 'en-gb.ar', 'AR'],
    ['Holidays in Australia', 'en-gb.australian', 'AU'],
    ['Holidays in Austria', 'en-gb.austrian', 'AT'],
    ['Holidays in Aruba', 'en-gb.aw', 'AW'],
    ['Holidays in Azerbaijan', 'en-gb.az', 'AZ'],
    ['Holidays in Bosnia and Herzegovina', 'en-gb.ba', 'BA'],
    ['Holidays in Barbados', 'en-gb.bb', 'BB'],
    ['Holidays in Bangladesh', 'en-gb.bd', 'BD'],
    ['Holidays in Belgium', 'en-gb.be', 'BE'],
    ['Holidays in Burkina Faso', 'en-gb.bf', 'BF'],
    ['Holidays in Bahrain', 'en-gb.bh', 'BH'],
    ['Holidays in Burundi', 'en-gb.bi', 'BI'],
    ['Holidays in Benin', 'en-gb.bj', 'BJ'],
    ['Holidays in Bermuda', 'en-gb.bm', 'BM'],
    ['Holidays in Bolivia', 'en-gb.bo', 'BO'],
    ['Holidays in Brazil', 'en_gb.brazilian', 'BR'],
    ['Holidays in the Bahamas', 'en-gb.bs', 'BS'],
    ['Holidays in Bulgaria', 'en-gb.bulgarian', 'BG'],
    ['Holidays in Botswana', 'en-gb.bw', 'BW'],
    ['Holidays in Belarus', 'en-gb.by', 'BY'],
    ['Holidays in Canada', 'en-gb.canadian', 'CA'],
    ['Holidays in The Democratic Republic of the Congo', 'en-gb.cd', 'CD'],
    ['Holidays in the Central African Republic', 'en-gb.cf', 'CF'],
    ['Holidays in Congo', 'en-gb.cg', 'CG'],
    ['Holidays in Switzerland', 'en-gb.ch', 'CH'],
    ['Holidays in China', 'en-gb.china', 'CN'],
    ['Christian Holidays', 'en-gb.christian', 'CHH'],
    ['Holidays on the Ivory Coast', 'en-gb.ci', 'CI'],
    ['Holidays in Chile', 'en-gb.cl', 'CL'],
    ['Holidays in Cameroon', 'en-gb.cm', 'CM'],
    ['Holidays in Colombia', 'en-gb.co', 'CO'],
    ['Holidays in Costa Rica', 'en-gb.cr', 'CR'],
    ['Holidays in Croatia', 'en-gb.croatian', 'HR'],
    ['Holidays in Cuba', 'en-gb.cu', 'CU'],
    ['Holidays in Cape Verde', 'en-gb.cv', 'CV'],
    ['Holidays in Cyprus', 'en-gb.cy', 'CY'],
    ['Holidays in Czech Republic', 'en-gb.czech', 'CZ'],
    ['Holidays in Denmark', 'en_gb.danish', 'DK'],
    ['Holidays in the Dominican Republic', 'en-gb.do', 'DO'],
    ['Holidays in the Netherlands', 'en_gb.dutch', 'NL'],
    ['Holidays in Algeria', 'en-gb.dz', 'DZ'],
    ['Holidays in Ecuador', 'en-gb.ec', 'EC'],
    ['Holidays in Estonia', 'en-gb.ee', 'EE'],
    ['Holidays in Egypt', 'en-gb.eg', 'EG'],
    ['Holidays in Eritrea', 'en-gb.er', 'ER'],
    ['Holidays in Ethiopia', 'en-gb.et', 'ET'],
    ['Holidays in Finland', 'en-gb.finnish', 'FI'],
    ['Holidays in Fiji', 'en-gb.fj', 'FJ'],
    ['Holidays on the Faroe Islands', 'en-gb.fo', 'FO'],
    ['Holidays in France', 'en_gb.french', 'FR'],
    ['Holidays in Gabon', 'en-gb.ga', 'GA'],
    ['Holidays in Grenada', 'en-gb.gd', 'GD'],
    ['Holidays in Georgia', 'en-gb.ge', 'GE'],
    ['Holidays in Germany', 'en_gb.german', 'DE'],
    ['Holidays in Ghana', 'en-gb.gh', 'GH'],
    ['Holidays in Gibraltar', 'en-gb.gi', 'GI'],
    ['Holidays in Greenland', 'en-gb.gl', 'GL'],
    ['Holidays in Gambia', 'en-gb.gm', 'GM'],
    ['Holidays in Guinea', 'en-gb.gn', 'GN'],
    ['Holidays in Equatorial Guinea', 'en-gb.gq', 'GQ'],
    ['Holidays in Greece', 'en_gb.greek', 'GR'],
    ['Holidays in Guatemala', 'en-gb.gt', 'GT'],
    ['Holidays in Guam', 'en-gb.gu', 'GU'],
    ['Holidays in Guinea-Bissau', 'en-gb.gw', 'GW'],
    ['Holidays in Honduras', 'en-gb.hn', 'HN'],
    ['Holidays in Hong Kong', 'en_gb.hong_kong', 'HK'],
    ['Holidays in Haiti', 'en-gb.ht', 'HT'],
    ['Holidays in Hungary', 'en-gb.hungarian', 'HU'],
    ['Holidays in India', 'en.indian', 'IN'],
    ['Holidays in Indonesia', 'en-gb.indonesian', 'ID'],
    ['Holidays in Iraq', 'en-gb.iq', 'IQ'],
    ['Holidays in the Islamic Republic of Iran', 'en-gb.ir', 'IR'],
    ['Holidays in Ireland', 'en-gb.irish', 'IE'],
    ['Holidays in Iceland', 'en-gb.is', 'IS'],
    ['Muslim Holidays', 'en-gb.islamic', 'MUH'],
    ['Hebrew Calendar', 'en.jewish', 'HEC'],
    ['Holidays in Italy', 'en-gb.italian', 'IT'],
    ['Holidays in Japan', 'en-gb.japanese', 'JP'],
    ['Holidays in Israel', 'en-gb.jewish', 'IL'],
    ['Holidays in Jamaica', 'en-gb.jm', 'JM'],
    ['Holidays in Jordan', 'en-gb.jo', 'JO'],
    ['Jewish Holidays', 'en-gb.judaism', 'JEH'],
    ['Holidays in Kenya', 'en-gb.ke', 'KE'],
    ['Holidays in Kyrgyzstan', 'en-gb.kg', 'KG'],
    ['Holidays in Cambodia', 'en-gb.kh', 'KH'],
    ['Holidays in Comoros', 'en-gb.km', 'KM'],
    ["Holidays in the Democratic People's Republic of Korea", 'en-gb.kp', 'KP'],
    ['Holidays in Kuwait', 'en-gb.kw', 'KW'],
    ['Holidays on the Cayman Islands', 'en-gb.ky', 'KY'],
    ['Holidays in Kazakhstan', 'en-gb.kz', 'KZ'],
    ['Holidays in Latvia', 'en-gb.latvian', 'LV'],
    ['Holidays in Lebanon', 'en-gb.lb', 'LB'],
    ['Holidays in Liechtenstein', 'en-gb.li', 'LI'],
    ['Holidays in Lithuania', 'en-gb.lithuanian', 'LT'],
    ['Holidays in Sri Lanka', 'en-gb.lk', 'LK'],
    ['Holidays in Liberia', 'en-gb.lr', 'LR'],
    ['Holidays in Lesotho', 'en-gb.ls', 'LS'],
    ['Holidays in Luxembourg', 'en-gb.lu', 'LU'],
    ['Holidays in Libya', 'en-gb.ly', 'LY'],
    ['Holidays in Morocco', 'en-gb.ma', 'MA'],
    ['Holidays in Malaysia', 'en_gb.malaysia', 'MY'],
    ['Holidays in Monaco', 'en-gb.mc', 'MC'],
    ['Holidays in Moldova', 'en-gb.md', 'MD'],
    ['Holidays in Montenegro', 'en-gb.me', 'ME'],
    ['Holidays in Mexico', 'en_gb.mexican', 'MX'],
    ['Holidays in Madagascar', 'en-gb.mg', 'MG'],
    ['Holidays in The Former Yugoslav Republic of Macedonia', 'en-gb.mk', 'MK'],
    ['Holidays in Mali', 'en-gb.ml', 'ML'],
    ['Holidays in Mongolia', 'en-gb.mn', 'MN'],
    ['Holidays in Macao', 'en-gb.mo', 'MO'],
    ['Holidays in Martinique', 'en-gb.mq', 'MQ'],
    ['Holidays in Malta', 'en-gb.mt', 'MT'],
    ['Holidays in Mauritius', 'en-gb.mu', 'MU'],
    ['Holidays in Malawi', 'en-gb.mw', 'MW'],
    ['Holidays in Mozambique', 'en-gb.mz', 'MZ'],
    ['Holidays in Namibia', 'en-gb.na', 'NA'],
    ['Holidays in Niger', 'en-gb.ne', 'NE'],
    ['Holidays in New Zealand', 'en_gb.new_zealand', 'NZ'],
    ['Holidays in Nigeria', 'en-gb.ng', 'NG'],
    ['Holidays in Nicaragua', 'en-gb.ni', 'NI'],
    ['Holidays in Norway', 'en_gb.norwegian', 'NO'],
    ['Holidays in Nepal', 'en-gb.np', 'NP'],
    ['Holidays in Oman', 'en-gb.om', 'OM'],
    ['Orthodox Holidays', 'en-gb.orthodox_christianity', 'ORH'],
    ['Holidays in Panama', 'en-gb.pa', 'PA'],
    ['Holidays in Peru', 'en-gb.pe', 'PE'],
    ['Holidays in the Philippines', 'en_gb.philippines', 'PH'],
    ['Holidays in Pakistan', 'en-gb.pk', 'PK'],
    ['Holidays in Poland', 'en_gb.polish', 'PL'],
    ['Holidays in Portugal', 'en_gb.portuguese', 'PT'],
    ['Holidays in Puerto Rico', 'en-gb.pr', 'PR'],
    ['Holidays in Paraguay', 'en-gb.py', 'PY'],
    ['Holidays in Qatar', 'en-gb.qa', 'QA'],
    ['Holidays in Réunion', 'en-gb.re', 'RE'],
    ['Holidays in Romania', 'en-gb.romanian', 'RO'],
    ['Holidays in Serbia', 'en-gb.rs', 'RS'],
    ['Holidays in the Russian Federation', 'en_gb.russian', 'RU'],
    ['Holidays in Rwanda', 'en-gb.rw', 'RW'],
    ['Holidays in South Africa', 'en_gb.sa', 'ZA'],
    ['Holidays in Saudi Arabia', 'en-gb.saudiarabian', 'SA'],
    ['Holidays in the Seychelles', 'en-gb.sc', 'SC'],
    ['Holidays in Sudan', 'en-gb.sd', 'SD'],
    ['Holidays in Saint Helena, Ascension and Tristan da Cunha', 'en-gb.sh', 'SH'],
    ['Holidays in Singapore', 'en_gb.singapore', 'SG'],
    ['Holidays in Sierra Leone', 'en-gb.sl', 'SL'],
    ['Holidays in Slovakia', 'en-gb.slovak', 'SK'],
    ['Holidays in Slovenia', 'en-gb.slovenian', 'SI'],
    ['Holidays in San Marino', 'en-gb.sm', 'SM'],
    ['Holidays in Senegal', 'en-gb.sn', 'SN'],
    ['Holidays in Somalia', 'en-gb.so', 'SO'],
    ['Holidays in the Republic of Korea', 'en_gb.south_korea', 'KR'],
    ['Holidays in Spain', 'en_gb.spain', 'ES'],
    ['Holidays in Suriname', 'en-gb.sr', 'SR'],
    ['Holidays in South Sudan', 'en-gb.ss', 'SS'],
    ['Holidays in Sao Tome and Principe', 'en-gb.st', 'ST'],
    ['Holidays in El Salvador', 'en-gb.sv', 'SV'],
    ['Holidays in Sweden', 'en_gb.swedish', 'SE'],
    ['Holidays in the Syrian Arab Republic', 'en-gb.sy', 'SY'],
    ['Holidays in Swaziland', 'en-gb.sz', 'SZ'],
    ['Holidays in Taiwan', 'en_gb.taiwan', 'TW'],
    ['Holidays in Chad', 'en-gb.td', 'TD'],
    ['Holidays in Togo', 'en-gb.tg', 'TG'],
    ['Holidays in Thailand', 'en-gb.th', 'TH'],
    ['Holidays in Tunisia', 'en-gb.tn', 'TN'],
    ['Holidays in Trinidad and Tobago', 'en-gb.tt', 'TT'],
    ['Holidays in Turkey', 'en-gb.turkish', 'TR'],
    ['Holidays in the United Republic of Tanzania', 'en-gb.tz', 'TZ'],
    ['Holidays in Uganda', 'en-gb.ug', 'UG'],
    ['Holidays in the United Kingdom', 'en_gb.uk', 'GB'],
    ['Holidays in Ukraine', 'en-gb.ukrainian', 'UA'],
    ['Holidays in the United States', 'en_gb.usa', 'US'],
    ['Holidays in Uruguay', 'en-gb.uy', 'UY'],
    ['Holidays in Uzbekistan', 'en-gb.uz', 'UZ'],
    ['Holidays in the Holy See (Vatican City State)', 'en-gb.va', 'VA'],
    ['Holidays in Venezuela', 'en-gb.ve', 'VE'],
    ['Holidays on the U.S. Virgin Islands', 'en-gb.vi', 'VI'],
    ['Holidays in Vietnam', 'en_gb.vietnamese', 'VN'],
    ['Holidays in Yemen', 'en-gb.ye', 'YE'],
    ['Holidays in Mayotte', 'en-gb.yt', 'YT'],
    ['Holidays in Zambia', 'en-gb.zm', 'ZM'],
    ['Holidays in Zimbabwe', 'en-gb.zw', 'ZW']
  ].freeze

  HOLIDAYS_WITH_CODES_MAPPING = HOLIDAYS_WITH_CODES.each_with_object({}) { |arr, hash| hash[arr[2]] = arr[1] }.freeze
end
