Ext.define("Freshdesk.view.ContactInfo", {
    extend: "Ext.Panel",
    alias: "widget.contactInfo",
    config: {
        itemId:'customerInfo',
        cls:'customerDetails',
        tpl:['<div class="customer-info">',
                '<div class="profile_pic">',
                    '<tpl if="avatar_url"><img src="{avatar_url}"></tpl>',
                    '<tpl if="!avatar_url"><img src="resources/images/profile_blank_thumb.gif"/></tpl>',
                '</div>',
                '<div class="customer-info-list">',
                    '<div class="title">{name}</div>',
                    '<tpl if="job_title"><div>{job_title}</div></tpl>',
                    '<tpl if="email"><div class="email"><span>&nbsp;</span>{email}</div></tpl>',
                    '<tpl if="mobile"><div class="phone"><span>&nbsp;</span>{mobile}</div></tpl>',
                    '<tpl if="phone"><div class="phone"><span>&nbsp;</span>{phone}</div></tpl>',
                    '<tpl if="twitter_id"><div class="twitter"><span>&nbsp;</span>{twitter_id}</div></tpl>',
                    '<tpl if="fb_profile_id"><div class="facebook"><span>&nbsp;</span>{fb_profile_id}</div></tpl>',
                '</div>',
            '</div>',
            '<div style="clear:both"></div>',
            '<tpl if="recent_tickets"><h3 class="title">Recent 5 tickets</h3>',
            '<ul class="ui-list_with_icon">',
                '<tpl for="recent_tickets">',
                    '<li><a href="#tickets/show/{helpdesk_ticket.id}"># {helpdesk_ticket.display_id} {helpdesk_ticket.subject}</a></li>',
                '</tpl>',
            '</ul></tpl>'].join(''),
        padding:0
    }
});